### ISSUE TITLE
Wrapped governance tokens need to rely on underlying() for total supply

### ISSUE THREAD

**Issue by herbig** [decentdao/decent-interface#1197]
### Overview

When using a wrapped governance token, we need to rely on the underlying token (`underlying()` function) for getting the total supply of the token.

Also, for proposal details specifically, we should be using the `votingSupply` on the proposal strategy struct, not the current total supply:

https://github.com/decent-dao/fractal-contracts/blob/develop/contracts/azorius/LinearERC20WrappedVoting.sol

### Additional Info

Here is an example of a wrapped governance token, with 0 total supply, since nothing is wrapped:

https://app.dev.fractalframework.xyz/daos/0x1d53C00c8b7FD7af9B370F464eF86BDf6324fa01/proposals/0

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/extensions/ERC20WrapperUpgradeable.sol

### Version

Dev (app.dev.fractalframework.xyz/)

**Comment by adamgall** [comment]
Stale, closing
