### ISSUE TITLE
Pending Snapshot Proposals say they have a longer wait time until they vote

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1325]
### Overview

Snapshot and Fractal UI's aren't aligning on the time until a snapshot proposal opens for vote

### Additional Info

Navigate tot his page - https://app.dev.fractalframework.xyz/daos/0x167bE4073f52aD2Aa0D6d6FeddF0F1f79a82B98e
![Screenshot 2024-01-22 at 10 24 53](https://github.com/decent-dao/fractal-interface/assets/31554133/75bf0d4c-250c-4c74-ac13-9f3f8bb482ff)

2) review the time left until vote as - 02:05:34:50

3) Then review the link here https://snapshot.org/#/lizardsdaos.eth/proposal/0x950bc398b64932edbe80ee5ce10245a23430f127fe920ee71aa2028623f4db90
![Screenshot 2024-01-22 at 10 25 27](https://github.com/decent-dao/fractal-interface/assets/31554133/fc986902-0c7a-4239-b894-a576ad769a63)

4) See that the pending time left should only be 3.5 hours 

### Version

Dev (app.dev.fractalframework.xyz/)

**Comment by tomstuart123** [comment]
@mudrila

**Comment by adamgall** [comment]
@tomstuart123 i'm not sure what's being shown in these screenshots. Fractal is showing a relative time, Snapshot is showing an absolute time, but without knowing what time it was when you took the screenshots i have nothing to anchor those things to.

Can you please give some more context? Am I right to assume (by the tense being used) that this is a problem that occurs when snapshot proposals _haven't started yet_?

**Comment by tomstuart123** [comment]
Yes the instructions I wrote aren't clear and I don't have a good enough memory to be exact. Lets leave this here until I have time to try and replicate this.
