### ISSUE TITLE
Treasury page - filter treasury for spam tokens

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1403]
See request here: 

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/ff64167f-290f-4f0b-acd9-77ba0f84a4d8)

I'm assuming they are looking at Shutter's treasury here.

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/0932d49b-666e-4076-ae88-f6499c067b04)

As you can see intended treasury tokens (ETH, SHU, USDC) are mixed with stakeEther.neet + UNI-V2

This is a tricky one as we don't want to filter out all tokens with $0 value (e.g. SHU (Shutter's native token) had $0 value originally but now is worth a lot of money). But at the same time we don't really want to get into the game of letting the user self filter

Saying that, some sort of ability to hide treasury coins seems interesting

**Comment by adamgall** [comment]
This should be pretty straightforward.

The Safe API endpoints that are used to get token balances have a couple of flags built right into them, to exclude "spam" tokens, or exclude "un-trusted" tokens, or both.

I'm not quite sure what the differences between those two flags are.

To see an example of how this would look for Shutter, do this:

1. visit https://safe-transaction-mainnet.safe.global/
2. expand the `GET v1/safes/{address}/balances` row
3. click "Try it out"
4. in the third input field, paste in Shutter's address: 0x36bD3044ab68f600f6d3e081056F34f2a58432c4
5. click on "Execute" to make the request
6. review the results
7. play around with the first two boolean flags
8. goto step 5

**Comment by tomstuart123** [comment]
Thanks. I just tested with an instance of Shutter's treasury and with Decent's treasury - 0xD26c85D435F02DaB8B220cd4D2d398f6f646e235

The first field (trusted) feels more effective in these two instances

Note - we'd still need a way for users to manually overidde in case the filtering gives them a heartattack if their token isn't appearing lol

**Comment by tomstuart123** [comment]
another data point from shutter to include when we look at this issue

I think making it toggleable locally could give users the best experience

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/ac514364-4456-4188-8a16-1b13c18134ca)

**Comment by tomstuart123** [comment]
- Filter Spam tokens
- utilise the first field 'Trusted' to filter
-  The piece that might need @decentdao/design is the 'toggle' aspect. 

As design has a lot on right now, we could start without this toggle aspect? I have some confidence in this filter for Shutter/Decent but haven't tested it with others

**Comment by adamgall** [comment]
Ok, will simply filter out the garbage for now. That's easy enough
