### ISSUE TITLE
create a proposal - myosin - 'why isn't send assets included'

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1413]
Myosin verbally (via video) gave feedback at how complex the flow is once you click 'Create a proposal'.

For his DAO most of the activities are just sending funds from one treasury to an address or multiple addresses.

They highlighted two issues trying to do this in Fractal

1) this screen is very complex and off putting if wanting to do something like a simple transaction

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/866f6c57-8cc5-4a31-874f-1af21070823d)

2) The send assets screen isn't flexible to send to multiple addresses easily. e.g. Why can't it be more liek the https://disperse.app/

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/aaf01443-aec8-44e4-b504-cf794358dd8a)

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/7251f319-42aa-4c4d-8b9b-46aca49e40d6)

**Comment by adamgall** [comment]
@tomstuart123 can we close this issue?

**Comment by adamgall** [comment]
Stale, closing
