### ISSUE TITLE
Fractal Docs broken link to X

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#1425]
The X link to “Follow Fractal” is broken. See screenshot. Check with @tomstuart123 for where this should point. 

<img width="1729" alt="CleanShot - Brave Browser - 2024-03-11 3@2x" src="https://github.com/decent-dao/fractal-interface/assets/18615633/3d9b155b-cc7c-459f-af16-ad81349d082c">

**Comment by adamgall** [comment]
Closing, this is fixed in new docs site: https://docs.decentdao.org/app
