### ISSUE TITLE
Creating proposal template and multisig proposal with description doesn't work due to issues with IPFS pinning

### ISSUE THREAD

**Issue by mudrila** [decentdao/decent-interface#1437]
While investigating https://github.com/decent-dao/fractal-interface/issues/1399 - I noticed that creating Proposal Templates, as well as creating proposal with description on Multisig DAO is broken due to issues with IPFS pinning. Need to fix that

**Comment by adamgall** [comment]
@mudrila is this still broken? AFAIK there aren't any longstanding issues with IPFS pinning. Can you please test again?
