### ISSUE TITLE
Don't rely on crawling logs to confirm that contracts are what we expect them to be

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1447]
There is at least one place in the app where we crawl through all events from various fractal master copy factories, to confirm that an address that we already have a reference to was deployed from that factory.

We need to remove that behavior.

Instead, we should be utilizing ERC-165 to have the frontend confirm with the contract that we already have a reference to, that it implements the functions that we expect it to implement.

Related to https://github.com/decent-dao/fractal-contracts/issues/73

**Comment by tomstuart123** [comment]
@adamgall - does this feel important?

**Comment by adamgall** [comment]
This is part of bigger maintenance work which will be necessary (I strongly believe) to remove our reliance on Alchemy as our RPC provider, and utilize the RPC provider brought to the app via connected wallets.

If you're asking whether or not it needs to stay in our backlog... idk. I don't mind it staying here.

**Comment by adamgall** [comment]
Stale, closing
