### ISSUE TITLE
Execute Button Go away after executing a multisig transaction

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#1511]
While this is kinda known issue. as it takes some time before Safe Transaction Service to index the transaction. We do have some polling in place. But we may want to relook at what we can do here. @adamgall changes to the loading proposals could help fix this as we can look into only updating a specific proposal rather than going refreshing all the proposals

![Image](https://github.com/decentdao/fractal-interface/assets/38386583/e404e184-afe3-4ec9-8cf1-7a5bd005909c)

**Comment by adamgall** [comment]
@Da-Colon is there a typo in the title? What's the issue here?

**Comment by adamgall** [comment]
Closing due to https://github.com/decentdao/decent-interface/pull/1990#issuecomment-2163179907
