### ISSUE TITLE
[Bug] DAO state resetting issue

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#1515]
Reproduce. (easy way to see it)

1. Go to any favorited DAO.
2. Open Favorites
3. Click on DAO currently viewing

This causes the DAO state to reset (due to a action.resetDAO on the button click).

But the dao is never refreshed.

**Comment by adamgall** [comment]
confirmed that this is still an issue

**Comment by Da-Colon** [comment]
On it
