### ISSUE TITLE
Sequential Proposal follow up -Caching

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1517]
This is follow up work from the PR here --> https://github.com/decentdao/fractal-interface/pull/1506 

As discussed with Adam at standup, there's room to extend proposals loading sequentially to add

- Cache completed proposals in local storage, so we don't need to re-fetch them.

My only additional thought is if completed proposals load faster, couldn't we get proposals coming in in the wrong order or confusingly.

Excited to pick this up though

**Comment by adamgall** [comment]
@tomstuart123 
> My only additional thought with (2) is if completed proposals load faster, couldn't we get proposals coming in in the wrong order or confusingly.
Nah, we sort them before displaying them. They can come in in any order but they'll always display in chronological order.

**Comment by tomstuart123** [comment]
adding shutter feedback for anyone fixing this issue

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/3feda59e-588f-4aaa-8e4c-f61c26b1b185)

**Comment by adamgall** [comment]
@DarksightKellar how is work going on this issue? Do you have any in-progress branches you can share?

**Comment by DarksightKellar** [comment]
> @DarksightKellar how is work going on this issue? Do you have any in-progress branches you can share?

@adamgall Just quick pushed this (no cleanup and I don't remember where I was. Probably adding some polish or something): https://github.com/decentdao/decent-interface/tree/cache-proposals

**Comment by adamgall** [comment]
> > @DarksightKellar how is work going on this issue? Do you have any in-progress branches you can share?
> 
> @adamgall Just quick pushed this (no cleanup and I don't remember where I was. Probably adding some polish or something): https://github.com/decentdao/decent-interface/tree/cache-proposals

Thanks @DarksightKellar! would you mind opening up a Draft PR for this branch?
