### ISSUE TITLE
Can't Favorite Multiple DAOs on hierarchy page

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#1533]
On the Hierarchy page, 

If you have multiple DAOs. if you click through to add multiple ones at the time, only one is actually saved to local storage, as on a refresh these won't update correctly leaving only one change saved (maybe two sometimes)

**Comment by adamgall** [comment]
@Da-Colon can you please test if this is still an issue?

**Comment by Da-Colon** [comment]
Yep, still an issue.
