### ISSUE TITLE
Execution order of multiple pending multisig transactions

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1536]
When there are multiple pending proposals, they *must* be executed in order of their nonces. Attempting to execute a nonce-7 proposal while a nonce-6 is pending fails with a non-descriptive error. If you go execute nonce-6, then nonce-7, that works fine. Tested with up to 4 pending proposals, and the behaviour is easily reproducible. This is likely expected behaviour though.

_Originally posted by @DarksightKellar in https://github.com/decentdao/fractal-interface/issues/1516#issuecomment-2049950031_

Adam's Notes:
We should be (but are probably not) disabling a multisig transaction's "Execute" button if it's nonce is not the next one that can be executed.

**Comment by Da-Colon** [comment]
> We should be (but are probably not) disabling a multisig transaction's "Execute" button if it's nonce is not the next one that can be executed.

Should we show the user an indication on why the button is disabled? I was thinking a tooltip on button hover? @decentdao/product @decentdao/design @adamgall

**Comment by adamgall** [comment]
@Da-Colon tooltip on hover sounds great, yes!
