### ISSUE TITLE
Onboarding — Share a (copyable) link to a new Safe after deploying a new Fractal DAO

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1538]
Since Fractal deploys a new Safe when a user creates a new DAO, this will give the user some visibility into what is happening during that process. Currently, it's not clear that a new Safe has been created, nor is there any way to access that Safe in the Safe app from Fractal's app.

**Comment by adamgall** [comment]
@decentdao/design @decentdao/product is there any priority to design and implement this workflow?

**Comment by nicolaus-sherrill** [comment]
The language and understanding here is a bit off, I admit, but would it be challenging to implement some sort of success screen w/ copy/pasteable safe address — is an offramping option to the Safe in the Safe app a good idea at this point?

**Comment by adamgall** [comment]
We could implement a success screen or modal which includes the new address and links to the Safe app (if we really wanna do that), sure.

**Comment by tomstuart123** [comment]
@nicolaus-sherrill / @adamgall - to be clear is this targeting new safe creation from app-home? Or any childSafe? Or both

The former, I do think is clunky right now and could be interesting to pick up now hats has had progress

**Comment by adamgall** [comment]
> @nicolaus-sherrill / @adamgall - to be clear is this targeting new safe creation from app-home? Or any childSafe? Or both
> 
> The former, I do think is clunky right now and could be interesting to pick up now hats has had progress

I think (but @nicolaus-sherrill plz confirm) this issue was about new Safe creation, from the Decent app home screen. Specifically, giving the user more visibility / accessibility (via Safe app) into the new Safe they just created.

**Comment by nicolaus-sherrill** [comment]
@adamgall yes, exactly.
@tomstuart123 given everything else, and my more developed understanding of how the product is being used, I do think this is a could, not a should at this time. A success screen would help bookend the Safe creation flow, but then that entire flow could also be simplified (visually) and stepped out better.

**Comment by adamgall** [comment]
Closing, stale
