### ISSUE TITLE
UX Writing — Clean up language about Fractal/Sub-Fractal/Sub-DAO/Fractal Safe/etc. across the app & documentation

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1540]
The language used to refer to what is created and what the user is interacting with in-app currently varies widely. Recommend standardizing language to align with "Safe" terminology, since Fractal is creating and managing Safes, and be clear when referring to the Safe itself vs the DAO functionalities.

1. Sometimes it is referred to simply as a DAO, seen here in the app home screen

![Image](https://github.com/decentdao/fractal-interface/assets/62394931/4e337bf4-332d-48ba-979f-7ffedf4c61fb)

---

2. Reference to "Create a Fractal" in the `Start from Scratch` flow

![Image](https://github.com/decentdao/fractal-interface/assets/62394931/2b536d7f-42ea-4eab-a106-36658a4d759b)

---

3. Sidebar refers to "Safe Home"

![Image](https://github.com/decentdao/fractal-interface/assets/62394931/c9271ae8-4f7b-4482-b477-c1667bfdfee2)

---

4. Hierarchy refers to "Parent Safe"

![Image](https://github.com/decentdao/fractal-interface/assets/62394931/66294ae0-96bc-45d0-aebd-0c428840dfb6)

---

5. Fractal docs kinda throw everything in the kitchen sink together: https://docs.fractalframework.xyz/home

**Comment by adamgall** [comment]
This is completed
