### ISSUE TITLE
UX Research — Conduct research to understand pain points and desires of Safe users.

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1541]
This may not be the right place for this type of note, but a few interviews and surveys could reveal some insights that Fractal may already solve and isn't specifically targeting in messaging, or can easily solve with a little work.

Gives us access to entire Safe user base and get an understanding of who could be a potential user that we are currently overlooking in marketing & biz dev efforts.

**Comment by adamgall** [comment]
Closing this issue, it's not actionable to the design or development teams.
