### ISSUE TITLE
DAO Dashboard (Safe Home) — Redesign layout and content DAO statistic cards to quickly signal most important metrics of DAO health

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1544]
This existing design does not have clear visual hierarchy. Regardless of the metrics being displayed, I can't currently get a good sense of what's important or whether a metric is a healthy indicator from the current visual hierarchy.

![Image](https://github.com/decentdao/fractal-interface/assets/62394931/20387254-23d5-4c63-bdc0-c7986b90ba13)

Suggested actions:

- Redesign this screen to be a 2-column content section with full width header card across the top.
- Adjust type styles and statistic card layouts to increase visual hierarchy of important metrics
- Update existing metrics to the most important metrics that signal DAO health.

Question to consider:
Which statistics are the most important to signal DAO health? (ex: # of proposals passed relative to total number of proposals, average participation %, etc.)

**Comment by adamgall** [comment]
@decentdao/design @decentdao/product is there any priority to design and implement these changes?

**Comment by nicolaus-sherrill** [comment]
Not a priority at this time but I do not want to lose this feedback for upcoming design sprints.

**Comment by tomstuart123** [comment]
There is a roadmap item to tackle DAO home. We're not there yet so lets leave this here @adamgall / @nicolaus-sherrill

**Comment by tomstuart123** [comment]
This in my opinion requires a whole PRD before it goes to design. 

THis shouldn't yet be an option for design pick up now that hats is done.

**Comment by adamgall** [comment]
Closing, stale
