### ISSUE TITLE
DAO Dashboard (Safe Home) — Add customization to DAOs via profile picture (logo), social links, and stats.

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1545]
The existing dashboard looks very sterile because there is no way to tell one DAO from another and I'm not forming any connections to the DAO I am looking at in the app.

- Add DAO PFP to main header card
- Add links to related DAO socials / ENS / Safe / websites
- - This could even be links to other DAO protocols, like Hats
- Include social stats to show when the DAO was created, # of favorites (follows?), the network the DAO is on, governance structure

**Comment by adamgall** [comment]
I'd like to close this issue, as it's not trivial to add these things to any given Safe. This would require a big design and development sprint. I don't think an issue should create for this until we decide to do it. I think this kind of comment would be better as a [Discussion](https://github.com/decentdao/decent-interface/discussions) until it's fleshed out enough to become actionable Issues.
