### ISSUE TITLE
Change "Favorite" language to "Follow"

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1546]
"Follow" is more social than "Favorite" and more accurate to how a user might expect to interact with a DAO they've chosen to stay more up-to-date with.
- Following a DAO could trigger push or email notifications when there is new activity, like voting or execution of transactions  (Related: #1548 )
- I, as a user, want to follow some DAOs even if I can't actively participate in their governance — that desired behavior is less clear with "Favorite"
- More social-based interactions appeal more to end-users like voters and other DAO participants and makes for easier bridge to community-based actions and platforms like Farcaster

**Comment by adamgall** [comment]
Closing, language has been updated to My Safes
