### ISSUE TITLE
Add a feedback button to the UI

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1547]
Capture in-the-moment feedback from all users, and feedback from users not currently in any established feedback channels.

Some quick options:
Temp check: 1-10 scale/thumbs up & down/frowny & smiley face for quick experience
Long form text submission: Detailed feedback response form
Optional to collect user info for direct follow up or filter to established feedback channels

- Would be rad to have a link for the user to submit feedback or share bugs as new Issues directly to our Github project.

**Comment by adamgall** [comment]
Added Sentry feedback button to app
