### ISSUE TITLE
XMTP — DAO Notification System

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1548]
Vote notifications
Subscribe to another user or DAO
Enable governance within chats

https://xmtp.org/docs/use-cases/dao

**Comment by adamgall** [comment]
Closing this issue, as it's not actionable in it's current form. @nicolaus-sherrill feel free to start a [Discussion](https://github.com/decentdao/decent-interface/discussions) about it so we can flesh out what effort it would take to implement, then we can turn it into a series of actionable issues.
