### ISSUE TITLE
Proposal List - Proposal Status badge is glitching for myosin.xyz

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1556]
In the first 2 mins of the video here - https://www.loom.com/share/3af51acc15ae4f3282c3287eebcc44d8

You can see that the proposal badge is jumping a lot between rejected (incorrect) and executed (the correct) on a 'netcetera guild'

By pausing it at EXACTLY at 1.19 you can see that the proposals are getting pulled for a micro second from another subDAO he was just on 'community guild'

See netcetera guild here - https://deploy-preview-1524.app.dev.fractalframework.xyz/proposals?dao=sep:0x18E5c68Fb3d3a5C4a5297143B90A1A7978EA94CF

See community guild here - https://deploy-preview-1524.app.dev.fractalframework.xyz/proposals?dao=sep:0x18E5c68Fb3d3a5C4a5297143B90A1A7978EA94CF

We had this issue before of subDAOs pulling proposals from other daos. Do we still have another issue for this or did we think this was fixed?

**Comment by adamgall** [comment]
The app needs a lot of TLC around how data is loaded. Closing this issue because I'm sure it's a symptom of deeper data loading / state issues, which are high on my "maintenance" priority list to refactor.
