### ISSUE TITLE
Push Notifications - Email / Telegram

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1557]
Shutter DAO have requested push notifications as proposals come in for their members

They already self-built a Telegram bot that alerts on proposals

Now they'd be interested in us incorporating email. 

I also think this PR should look at their telegram bot and see if we want to build a cohesive experience around push notifications across both channels 

_Challenges_
-  note this isn't without its challenges. If we do email signup, where are we storing the email? We only have a server for one small piece of the app if I remember. Lets discuss

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/91f44d6e-38d9-4b82-9f10-eb24b4558361)

_Future work_
- in the future we should also think about social nudges (e.g. twitter/warpcast)

**Comment by adamgall** [comment]
Much lik https://github.com/decentdao/decent-interface/issues/1548, I'm closing this issue because it's not very actionable. Let's open a [Discussion](https://github.com/decentdao/decent-interface/discussions) if we want to flesh it out more.
