### ISSUE TITLE
Proposal Page - Time Misalignment between Toaster execution alert and the execution button

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1558]
See video at 5.23 and 3.23

https://www.loom.com/share/3af51acc15ae4f3282c3287eebcc44d8

When the toaster pops up showing a 'executed successfully' for a brief second the button on the proposal page (currently greyed out as it should be) will light up orange again. If the user clicks it, it will error (as expected) ... but why is it lighting up at all (i.e. prompting a user action)

There's clearly a lag when the UI hasn't fully caught up with the toaster on the current proposal status. 

This lag maybe impossible to fix, ...but lets explore removing the 'light up' of the button. The button should remain grey until an actual transaction possibility is on the cards

**Comment by tomstuart123** [comment]
@adamgall this one I'd like to bring to Ready column. 

Is there more detail needed here?

**Comment by adamgall** [comment]
I don't think there's any more detail needed. My only question is, does this still occur? Is it consistent? @tomstuart123

**Comment by tomstuart123** [comment]
I'll try and replicate by end of day

**Comment by Da-Colon** [comment]
I'm assuming this is Multisig Safe?

**Comment by tomstuart123** [comment]
Sorry for the delay on this @adamgall / @Da-Colon. I finally, got to this and was able to replicate this . It happens on

1) timelock execution  - very briefly  (like 1 second) 
2) execute tx - much longer (I was able to click between screens and return to see the button still open to clicking. If i clicked i got the same error messaging

See video for the number 2) - https://decentdao.slack.com/archives/C06QZTUTKRC/p1717496070661879?thread_ts=1717419826.480139&cid=C06QZTUTKRC

See [link to Safe i](https://app.dev.decentdao.org/proposals/0xe7689e490c03228de90630fc787b737a7380aa7b9ed8143bc107bf50109f18fb?dao=sep:0x773eC5B85aebAa323e700E9bbAA7Cb2eFeAdf56F)t happened on

**Comment by tomstuart123** [comment]
Would like to get eyes on this so moving to P1

**Comment by adamgall** [comment]
@DarksightKellar is #1511 related to this issue too?

**Comment by tomstuart123** [comment]
@adamgall - it sounds similar.... but I'm still not entirely sure what 1511 is meant to do. 

@Da-Colon if you can confirm what you meant in the above issue?
