### ISSUE TITLE
Show more accurate loading indicators when Proposals are sequentially loading in

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1567]
When proposals are loading in, we should improve the experience in two ways:

1. Don't show "No Proposals" component when the first proposal is loading in.
2. Indicate to the user that proposals are still coming in, until they're finished.

Probably need some design assistance for the new component for 2. above.

**Comment by tomstuart123** [comment]
UPDATE 

This was originally a part of proposal here - https://github.com/orgs/decentdao/projects/32/views/3?pane=issue&itemId=58714144

We split this out into two PRs as they are different tasks
