### ISSUE TITLE
Bug: Back Button DAO not unloading/reloading

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#1582]
Reproduce. 

- Go to a DAO. 
- Use favorite menu to go another DAO
- Hit Back button

- The address and DAO info updates. but proposals state doesn't reset.

**Comment by adamgall** [comment]
@Da-Colon is this still happening?

**Comment by tomstuart123** [comment]
Yep, I was able to reproduce this.

Even weirder, the 2nd DAO i Navigated to had its proposals show in the 1st DAO I went back to . 

See below where Myosin's proposals are appearing in my test DAO's proposal list

![Image](https://github.com/decentdao/decent-interface/assets/31554133/099d28c9-a0fd-467b-9a0f-1b6018d7727b)
