### ISSUE TITLE
Top nav animation transitions

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#1672]
**Page/Section/Component**
Top Nav, all interaction transitions globally

**What is the problem?**
Top Nav lacks animation transition, hover state appears instantly on buttons

**Why is this a problem?**
Without the transition property set, the state changes appear instantly and not as a smooth animation

**Solution**
set default transitions to `ease-out` at `300ms`

**Comment by adamgall** [comment]
@Da-Colon is this something we could implement in `decent-ui`?

**Comment by tomstuart123** [comment]
I'd love more details on this and if it can be moved to ready or if design needs to unblock?

**Comment by Da-Colon** [comment]
@adamgall @tomstuart123 @xraystyle1980 Sorry for the delay, totally missed this one mention. yeah For buttons we could do this globally, Someone of the non-themed components we will need to apply this bit by bit (I believe). I'll take this one on.
