### ISSUE TITLE
Proposal Loading - # of proposals at the top should be total

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1675]
Currently as the app loads proposals, the ticker at the top also increments them one by one

e.g. 

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/3e0c6ae5-5d68-46e1-b2a6-afb51ead6f12)

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/a59de0f1-7140-4816-99f0-b98cd1d72411)

This can confuse the user. E.g. in the above, does AwakeVC have 0 proposals total or 4 proposals total. Are more coming? Will it increment more

My take is the top nav should show the total proposals immediately OR if thats not possible have a loading/tbd filler until all the proposals are confidently. found

# TO DO

- Replace the two proposal numbers in that card with:
  - Total number of proposals. Show this number immediately as DAO is loaded.
  - Number of "pending" proposals. We won't know this number until all proposals (and their state) are loaded. Show a "Loading..." message as that value until ready.
    - Actually, we might be able to get this number before all proposals are loaded. As soon as we hit a proposal that is _not_ pending (because we're loading them from the most recent, backwards), the chances are super low (zero?) that no more will be pending.
    - edit: actually, not that easy. "Pending" (in its current meaning on this component) means all "active" proposals (where voting is open), _and_ all "executable" proposals (where voting is closed, it has succeeded, but hasn't been executed yet). There might be the case where there are executable proposals which are _older_ than non-executable proposals. Although, in this case, I might just make the executive decision that if we run across any of those, just add to the number that has already been determined to display.

**Comment by adamgall** [comment]
@tomstuart123 the numbers at the top of the page don't show "total proposals". they show "passed" and "pending". we _do_ know the "total" number immediately, but we don't know the state of them until they're loaded in.

With that in mind, what do you want to do with this issue?

**Comment by adamgall** [comment]
@tomstuart123 I don't think this is ready for engineering yet. Please describe what numbers you want to see in that Dashboard card.

**Comment by tomstuart123** [comment]
Yep lets keep it in backlog until we have consensus.

@nicolaus-sherrill / @adamgall - my take is:
--> we should have a total proposals # - _reason_ = a sign of DAO activity AND user reassurance whilst proposals load  (see screenshot shutter feedback below)
--> pending is also important - reason = a sign that action is required (however - to the point at the top, I don't think this should increment one by one. Instead, I think it should have a loading icon UNTIL state is updated and we know total pending proposals)
--> I'm not sure 'Passed' and 'Failed' are required here (but I'd love to be challenged here and have your takes @nicolaus-sherrill / @adamgall ). Shutter nor Myosin have specifically given feedback to this point
![Screenshot 2024-05-24 at 11 55 12](https://github.com/decentdao/decent-interface/assets/31554133/e0562674-1e31-4912-b749-cb8c6e2add01)

**Comment by tomstuart123** [comment]
@nicolaus-sherrill - what about you?
