### ISSUE TITLE
Nested menu design

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1679]
For patterns in the UI where there are nested menus (such as network selector in top nav and language selector), we should have a better pattern for how to handle those. Screenshot examples below:

![Image](https://github.com/decentdao/fractal-interface/assets/62394931/ede23955-9df9-48a2-abce-32d93732b990)
![Image](https://github.com/decentdao/fractal-interface/assets/62394931/ea2a30a7-a355-4b58-b77d-776bb5b02a67)

**Comment by xraystyle1980** [comment]
Wallet menu in design system with nested menu switcher is ready
https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=2168%3A20014&t=QRpmoGVZcRiSRtD3-1

![image](https://github.com/decentdao/fractal-interface/assets/18615633/45f39a09-ad3f-48ed-992f-dd41bc878ec2)

**Comment by xraystyle1980** [comment]
@nicolaus-sherrill Sidebar language nested menu. I think just using the same expanded sidebar menu component is the way to go. Mocked up here https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?node-id=2919-7224&t=QRpmoGVZcRiSRtD3-4

![image](https://github.com/decentdao/fractal-interface/assets/18615633/fec95bc4-a180-4e37-91c8-459c73781170)

**Comment by adamgall** [comment]
@decentdao/design does this issue still need to be open?

**Comment by nicolaus-sherrill** [comment]
@adamgall well without a languages menu option, I would think not.
