### ISSUE TITLE
Text link style

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#1680]
We discussed this in Design Jam this morning (5/8/24), and seems like there is an actual need for it.

For better functionality and consistent performance of the ghost-hover text buttons, we should have a new style for text links that go to external sites.

Ghost text buttons for internal pages. Text links for external pages.

We looked at an underline style this morning. Good place to start.

**Comment by xraystyle1980** [comment]
Text links are [here in Design System](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=2248%3A24732&t=0rgM7lEZanxpdvHM-1)

![image](https://github.com/decentdao/fractal-interface/assets/18615633/7fe3c283-bf0e-435d-adb8-fefecbd9a001)

**Comment by adamgall** [comment]
@decentdao/design does this issue still need to be open?

**Comment by nicolaus-sherrill** [comment]
I believe this was updated and is reflected live.
@xraystyle1980 please confirm and close.
