### ISSUE TITLE
Proposal Details Voting Power Tooltip

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1690]
**Proposal Details Voting Power Tooltip**
Text on voting power tooltip is too long. Please wrap text to match other tooltip designs
![CleanShot - Notion - 2024-05-08 3@2x](https://github.com/decentdao/fractal-interface/assets/18615633/a17507c6-48ab-41bc-b184-f22f9790369d)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101323779_

**Comment by tomstuart123** [comment]
done

**Comment by adamgall** [comment]
Closing
