### ISSUE TITLE
Pending/Passed proposal count incorrect

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1707]
**delma.betancourt left a comment:**

on my end - dont see that 1 pending, 1 passed for proposals. matt sees the accurate count of proposals 

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiIyM2MyNDJlNy05MTE4LTQyM2YtYjYxNi0zMzVhZGI2NDZkYTgifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Chrome 123.0.0.0 on Mac OS 10.15.7
Viewport:  996 x 958 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=123.0&resolution=996x958&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb17453262b079ea738b8&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101032252_

**Comment by Da-Colon** [comment]
Was this caused by the recent Viem updates? or is this still an issue on `reskin` branch

**Comment by adamgall** [comment]
I would argue that the screenshot in this issue is accurate. There are no pending or passed proposals being displayed. There is one "timelocked" transaction being display.

Flagging @decentdao/designers @tomstuart123. Perhaps we need to backlog an issue (not for this reskin) to rethink the contents of that "Proposal" card. As is, it doesn't encompass all of the different states that a proposal might be in, as indicated in this issue.

**Comment by tomstuart123** [comment]
yep agree. This isn't clear rn but needs thought

**Comment by adamgall** [comment]
Ok, i'm going to remove the `design` label from this issue then. Thanks @tomstuart123

**Comment by adamgall** [comment]
Closing as duplicate: https://github.com/decentdao/decent-interface/issues/1675
