### ISSUE TITLE
Cross network favorites

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1710]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJkNWQyYzczMy1jMmZjLTQyMmItODIwZi1jYjdmYTkxYjA4ZGMifQ==)

Can we make favorites viewable across networks? Currently seeing no favorites if on a different network. Means we're asking users to manage multiple favorites lists.

<details><summary>Browser metadata</summary>

```
Path:      /home?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1402 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Deth%3A0xD26c85D435F02DaB8B220cd4D2d398f6f646e235&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1402x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663baeeacc87930557124f80&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101014045_

**Comment by adamgall** [comment]
I think this is outside of the scope of the reskin, but a good idea regardless. Will require more design and engineering brains to implement though.

**Comment by Da-Colon** [comment]
yep not to bad actually. You've set up the ground work with the new query. and wouldn't be much to sort and reorg the list into a object by network. then just add a label between each section? We have the patterns for 'labels' with the Wallet Menu so could be a easy win.

**Comment by nicolaus-sherrill** [comment]
Word!

To @Da-Colon 's point, two quick solutions:
1. Add network icon to Favorite list item
2. Segment list by network

Even though we're going to be removing the DAO index from the home page, this same functionality is intended there too. User should be able to view DAOs across chains & possibly filter down (let's us display more DAOs in the index at once = better look for BD).

**Comment by adamgall** [comment]
This is completed
