### ISSUE TITLE
Multisig Timelock Period missing

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1719]
7) @adamgall for some reason my Multisig Safe doesn't show the timelock period whilst the fractal.dev UI does for the same safe? 
![Screenshot 2024-05-06 at 12 53 16](https://github.com/decentdao/fractal-interface/assets/31554133/f8144d5c-683a-4539-8f5c-5b92e441e6cb)
![Screenshot 2024-05-06 at 12 53 12](https://github.com/decentdao/fractal-interface/assets/31554133/651e42ce-2082-44aa-b0ca-62fb4e8fe3f4)

Any ideas?

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096392695_

**Comment by Da-Colon** [comment]
Might take some looking into. Might be an opportunity to move this value from being gathered on DAO load to just use Wagmi/Viem batch and caching to help. As there will very fine tuned timing on the loading of the DAO info,  to check if the DAO loading is a childDAO or not.

**Comment by tomstuart123** [comment]
<img width="870" alt="Screenshot 2024-05-09 at 12 09 55" src="https://github.com/decentdao/fractal-interface/assets/31554133/3fe8e65a-7c35-47ec-9576-82d8f94a9db5">

@adamgall / @Da-Colon I just reopened this specific DAO in app.dev. and production and there was now no timelock (.. shrug)

Going to remove the 'reskin' tag as clearly its a different issue. Lets pick it up when reskin is done

**Comment by tomstuart123** [comment]
@adamgall - not moving this to p2... but am moving it into backlog until we reproduce it more

**Comment by adamgall** [comment]
closing this issue because i would bet it's a symptom of poor data loading and state management patterns.
