### ISSUE TITLE
Getting "Home" while on mobile

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1725]
Non-reskin related weird UX for me that we should pick up in the future as an issue

--> @adamgall / @nicolaus-sherrill / @xraystyle1980 - I don't feel like its intuitive getting back to the app homepage when in a DAO on mobile. You have to press the top left logo once, wait for the side bar, then click the top left logo again

Lets look at this after reskin unless someone says this is intended functionality and why

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096407242_

**Comment by Da-Colon** [comment]
Mobile hasn't gotten enough justice in the past. This drawer wasn't meant to be permanent. I like @nicolaus-sherrill 's idea of creating a floating menu of some kind on the bottom instead of using the drawer. 

But this doesn't really solve 'going home' since We cant fit everything in there.

**Comment by tomstuart123** [comment]
agree. lets wait until reskin complete to pick this up.

**Comment by nicolaus-sherrill** [comment]
@adamgall @Da-Colon @tomstuart123 100% agreed with everything above. I feel similarly about that functionality — it's a lot of steps!

Just you wait y'all. You thought the new sidebar was my full power? That was only a fraction of my power.

New floating menu (properly positioned as a bottom-screen tray on mobile) is a big want of mine as part of bigger upgrade to app navigation.

**Comment by adamgall** [comment]
Closing this issue, nothing actionable here.
