### ISSUE TITLE
Data loss on refresh

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1729]
If you get stuck on deploying on mobile and refresh all your data is lost 
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Mobile Safari 17.4.1 on iOS 17.4.1
Viewport:  393 x 651 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663baa041b3b48008af4d561&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2100971410_

**Comment by adamgall** [comment]
@azadikoff do you expect that the input fields retain their data between refreshes?

**Comment by azadikoff** [comment]
Yes, that would be preferred but it’s not a p0 issue.

**Comment by Da-Colon** [comment]
Not sure how to mark this? This is not related to reskin as this functionality was there prior. Should probably remove the reskin label on this one.

**Comment by tomstuart123** [comment]
agree. just due to the amount of stuff, I'll move to p2 / no reskin tag

**Comment by adamgall** [comment]
Closing, not reasonable to implement now
