### ISSUE TITLE
Give user feedback that something is happened after new DAO deployment

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1732]
After deploying you don’t get any indication that something is happening. It should start loading or a spinner immediately 
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Mobile Safari 17.4.1 on iOS 17.4.1
Viewport:  393 x 659 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bac3dfdde9d00a516a5a3&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2100995373_

**Comment by Da-Colon** [comment]
Can we get some Direction from Design? @nicolaus-sherrill @xanaramoss @xraystyle1980

**Comment by tomstuart123** [comment]
ye this will probably need some thought. @nicolaus-sherrill shall we look at this once we feel better about homepage first?

**Comment by nicolaus-sherrill** [comment]
@tomstuart123 I was about to suggest the same thing.
This could be visually solved with a toast or a new "waiting" screen relatively quickly, but let's not rush to a solution right away.

Do we feel this is a critical breaking UX frustration that should be solved before launch?

**Comment by adamgall** [comment]
Closing
