### ISSUE TITLE
Safari Mobile + CB Wallet deployment issues

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1733]
Can’t deploy from safari mobile with Coinbase wallet mobile but you can from the cbw in app browser
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Mobile Safari 17.4.1 on iOS 17.4.1
Viewport:  393 x 659 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bac62e4a6a300981d5a76&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2100997155_

**Comment by adamgall** [comment]
@azadikoff what happens?

**Comment by azadikoff** [comment]
I'll try to screen record later but when you are redirected back to the wallet app, no signing modal appears. The expectation is that the site passes the data to the app through a deep link and the app is prompted to display the signing interface. If this is done within the wallet's in app browser it works just fine.

**Comment by azadikoff** [comment]
Here's a screen recording. https://drive.google.com/file/d/1h75z7VkQOJQCD_DK0hwiHF2ET8j81QnL/view?usp=drivesdk

**Comment by Da-Colon** [comment]
Interesting. I don't think much testing has been done via Safari. Have we tried Chrome Mobile? most likely unrelated to `reskin` so label can probably be removed

**Comment by tomstuart123** [comment]
I just tried chrome mobile (note android phone) and it worked.

Thinking this is an ios or safari specific issue

**Comment by adamgall** [comment]
Removing this `re-skin` label from this.

**Comment by tomstuart123** [comment]
@adamgall - agree its on reskin and agree keep it in backlog until an iphone user can replicate

Saying that, if I can find someone with an iphone who can replicate this, then we should try and get this in pre the launch

**Comment by tomstuart123** [comment]
Reasoning - most people at the event will be on mobile and will default to safari

**Comment by adamgall** [comment]
Ok, reviving the `re-skin` label then, seems liek this is important

**Comment by adamgall** [comment]
@azadikoff can you please try this again on https://deploy-preview-1578.app.dev.fractalframework.xyz? I just updated our web3 libraries, shot in the dark but maybe that fixes it.

bigger comment here is that i don't think there's much we're going to be able to do _in our codebase_. i suspect that any issues like this will be bugs or issues of the web3 wallet connection libraries we're using.

**Comment by tomstuart123** [comment]
UPDATE @adamgall  - @azadikoff was able to still replicate this issue (see his note [here](https://decentdao.slack.com/archives/C06QZTUTKRC/p1715359200267879?thread_ts=1715353726.616559&cid=C06QZTUTKRC)) as well as a new issue.

Tom was able to replicate the new issue and created a github issue here (https://github.com/orgs/decentdao/projects/32/views/3?pane=issue&itemId=62720197)

The issue above, I still couldn't replicate so still looking for an extra iphone user to try.

**Comment by tomstuart123** [comment]
Summary from bug bash. Many users had issues with CB wallet on mobile

See --> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2117962696

**Comment by adamgall** [comment]
Closing, this is not reproducible enough to take priority
