### ISSUE TITLE
Delegate vote isn't working for some people

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1737]
Lots of Decent members unable to delegate to self - 

https://decentdao.slack.com/archives/C06QZTUTKRC/p1715261499103099?thread_ts=1715261333.598799&cid=C06QZTUTKRC

Before a dev picks this up, let Tom try and replicate it

**Comment by tomstuart123** [comment]
Trice was creating a new DAO. Delma saw the ability to delegate. Came back and lost the ability to see the delegate button

Xana had transaction failed.

@xraystyle1980 / @tomstuart123 to try and replicate. Will comment below

**Comment by tomstuart123** [comment]
Still can't replicate this. Will ask people specifically in bug bash

**Comment by tomstuart123** [comment]
@adamgall - lots of people faced this issue in bugbash

See mine here - https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2118026461

I would say half the room also

**Comment by adamgall** [comment]
Closing, this isn't reproducible enough to take priority.
