### ISSUE TITLE
Error on allocation before user inputs anything

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1738]
**dara.khan left a comment:**

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYmVlNWZhYTA4OWIwMDA5ODJhODg4IiwiaWQiOiI2MzE0MjRmZS04YjM2LTQ3ZTktYWNmNy0yOGI0OTlmNzY2MzMifQ==)

Throws an error/red text before you even get to do anything, i.e. clicking [Add Allocation] immediately puts a red-text/error up before you even get to fill something out. 
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1720 x 717 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1720x717&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663bee5faa089b000982a888&commentID=663c30ce83bcab3cdd0aa78a&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101803357_

**Comment by Da-Colon** [comment]
@tomstuart123 What are your thoughts on this. We could just remove this error and remove empty address/amount in the background. or do as @mudrila suggested and change the text of the error and let the user know that they need to remove empty inputs

**Comment by tomstuart123** [comment]
I like @mudrila 's reco. The copy is kinder for sure but not sure I understand the other option fully

@Da-Colon could you clarify what you mean around 'remove empthy address/amount in the background'. How would this work?

**Comment by adamgall** [comment]
It seems like a misconfiguration of our validation solution here that we're seeing an error message before the user types anything into the input field, and before the user clicks the continue button.

Why isn't Yup handling this more gracefully? Let's find and fix the underlying problem here.

**Comment by Da-Colon** [comment]
> I like @mudrila 's reco. The copy is kinder for sure but not sure I understand the other option fully
> 
> @Da-Colon could you clarify what you mean around 'remove empthy address/amount in the background'. How would this work?

I was saying that we can write some custom error logic that if allocation is reached and if a row doesn't contain a value or an address, we allow the next button be hit and 'clean up' empty values. 

to @adamgall 's point it might be better to just do better error handling here. I believe that is currently handling these similar to how He layout it out in his comment. Just want to make it clearer for the user why this error is happening

**Comment by tomstuart123** [comment]
I'd be down to just use the error message for 'invalid inputs' rather than empty inputs (if I understand your scenarios correctly @adamgall )

**Comment by adamgall** [comment]
@mudrila would you mind please recording a video showing the current behavior of this component? That would help us decide what to do here.

- make sure the "next" button is visible in the video (so we can see when it is enabled/disabled)
- show what happens when new rows are added
- show what happens when valid data is inputted
- show what happens when invalid data is inputted
- basically try to manipulate the UI so that all possible states are displayed

Thank you! I am at the doctor right now else I would do this myself.

**Comment by tomstuart123** [comment]
@adamgall / @mudrila - 1 recording here


https://github.com/decentdao/fractal-interface/assets/31554133/823800c0-2127-4cb9-a601-53ace34089f9

looking above, this didn't cover invalid data. I'll quickly do another one

**Comment by tomstuart123** [comment]
recorded again for invalid data. inputs only accept decimals and numbers. Letters weren't allowed. The red error arose when 1) no number in input field and 2) when a number too large for the total token amount is inputted

https://github.com/decentdao/fractal-interface/assets/31554133/9b76f652-a914-44b3-9491-6e6f4fe7ab1c


No error when decimals used. Two errors for some reason when the bottom row had a number too large

**Comment by adamgall** [comment]
Thanks for the video @mudrila. Honestly, there's nothing about this behavior that stands out as problematic to me.

@decentdao/design @decentdao/product thoughts?

**Comment by tomstuart123** [comment]
the only weird part for me was in the 2nd video. When I added a token allocation that was over total amount to the 2nd row, an error appeared on that row AND the row above it.

skip to 0.45 secs

**Comment by adamgall** [comment]
@tomstuart123 

ok so, if any one single row has a token amount greater than the total token amount, just that row should populate an error.

but if all rows have token amounts lower than the total token amount, but the sum of all of those rows is greater than the total token amount, i expect we'd want to see an error on all rows?

**Comment by DarksightKellar** [comment]
Probably the safest thing to do is the latter -- global error message not tied to any single row. And a copy update like @mudrila initially suggested. `Invalid token allocation` is too cold.

**Comment by tomstuart123** [comment]
I see your point @adamgall. The latter is then also my preferred. 

Saying that, I think this conversation has proven the current UX is mostly fine. We can at some point pick up this additional global error.. but not a hard requirement pre next week is my take

**Comment by adamgall** [comment]
Closing, not priority.
