### ISSUE TITLE
DAO times (proposals, timelocks, etc) in "minutes" are confusing

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1744]
When creating the token, was confused as to why times are in minutes instead of days for creating the proposal, etc. usually dont think of deadlines in terms of minutes. counterintuitive
<details><summary>Browser metadata</summary>

```
Path:      /home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Chrome 123.0.0.0 on Mac OS 10.15.7
Viewport:  996 x 958 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=123.0&resolution=996x958&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bae0efc253b034a6c110a&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101008176_

**Comment by adamgall** [comment]
@tomstuart123 @decentdao/designers what's your take on this. Something to update/change during the reskin?

**Comment by tomstuart123** [comment]
Post reskin.

Mike and I struggled with this back in the days. Days probably makes the most sense eventuallly but user would lose some granularity. I'm sure there's a middle ground but lets not worry about it until after

**Comment by adamgall** [comment]
Will remove `re-skin` label.

**Comment by adamgall** [comment]
Closing, not priority. This is a thing that is set once per DAO, and giving people the resolution of minutes seems not too small. Hours seems too big.
