### ISSUE TITLE
Favorites / Settings feedback

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1748]
The Favorites Tab and Settings Tab button don't pop up. Its hard to see these. It would be helpful to have favorites and settings as part of the menu option to the left - either grouped with safe home - templates, or grouped with FAQ- language

If Im invited in the DAO and got some coins - expecting to see the DAO in my favorites 

There should be an add to favorites function automatically

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJiZDljYTA2ZC1hYTRiLTQ2N2YtOTEyMy02NzNiMDUyYzMyOGUifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Chrome 123.0.0.0 on Mac OS 10.15.7
Viewport:  996 x 958 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=123.0&resolution=996x958&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663badbb180cc10467869367&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101006075_

**Comment by adamgall** [comment]
@nicolaus-sherrill @xraystyle1980 @xanaramoss leaving this to you

**Comment by nicolaus-sherrill** [comment]
Considering that this is more of a UX request, I think we should shelve until completing reskin.
@tomstuart123 thoughts?

**Comment by tomstuart123** [comment]
agreed. I actually think the settings page is a no brainer... but we need to think about what goes here. The members page, the settings page... I'm sure there more

Important.. but not urgent.

**Comment by adamgall** [comment]
Going to remove the `re-skin` label from this then.

**Comment by adamgall** [comment]
Closing, not priority
