### ISSUE TITLE
Apply padding to main container

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#1809]
See this comment for context: https://github.com/decentdao/fractal-interface/pull/1794/commits/a4140d5de5a951545ebd4946200f0e9fb4b4a0eb#r1604859664

This is a codebase maintenance issue, functionally and visually nothing changes.

Note:
The DAO Home has a top padding of 1.5, instead of the more widely used 3 rem. Need to factor this in if intentional from design, otherwise update design.

**Comment by adamgall** [comment]
Closing, not priority
