### ISSUE TITLE
Helper text for initial allocations

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1811]
**delma.betancourt left a comment:**

Would be great to have more context and info on each of these screens - as a user I want to know whats happening and why, more context on each of these sections

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiI2ODJiN2ZhMi1jMTI1LTRmZTEtYmE3OS03YzBmOTAxZTkzMTIifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 123.0.0.0 on Mac OS 10.15.7
Viewport:  1307 x 958 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=123.0&resolution=1307x958&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=66478402d44591e8dd95f221&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117947161_

**Comment by adamgall** [comment]
I can't think of what other context we could put on this page. You have no right to be creating a DAO if you don't know what Name/Symbol/TotalSupply of an ERC20 token are, or if you don't understand the concept of minting that token to different addresses.

Closing.
