### ISSUE TITLE
Assign Names to Addresses(ENS lookup?)

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1813]
**delma.betancourt left a comment:**

would be great to be able to assign names to wallet addresses for admin. Zadi recommended maybe at least using ENS lookup as a hack until then

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiI3YzQ4N2JmOS1kN2VlLTQwMWQtYjdjZi01MmE3MTY0MzEzMmQifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 123.0.0.0 on Mac OS 10.15.7
Viewport:  1307 x 958 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=123.0&resolution=1307x958&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=664784ff1ee1d0f61700dc19&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117952876_

**Comment by adamgall** [comment]
Closing, this request doesn't make sense
