### ISSUE TITLE
Copy - commas or not?

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1814]
**dara.khan left a comment:**

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiI1Y2IzNDVjMy05MDExLTQ1NWItYjQ0My1mOGI3ZWZiZTgzMjYifQ==)

In some places we use commas in the preview-prompt in the box to be filled out for numbers, but in others like total token size, we don't. Suggest we go with only commas for numerics auto-populated if possible for easier reading. 
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1011 x 817 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1011x817&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=664785b61ee1d0f7bd00db25&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117958404_

**Comment by adamgall** [comment]
Closing, i see commas in both Total Supply and Amount inputs

<img width="963" alt="Screenshot 2024-05-22 at 5 08 34 PM" src="https://github.com/decentdao/decent-interface/assets/706929/5aeffd8e-7a7c-47d6-a29a-e43c8bc34be3">
