### ISSUE TITLE
Change language on DAO token setup

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1815]
**delma.betancourt left a comment:**

Would change language to make it clearer that once this setting is applied the only way to change it will be via a vote. Put it at the top of the page and large text to highlight how important these features are

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiIwZjIwM2Y2YS0xOTA3LTRjMTMtYmUyNC1lZjEyNWJlNWVkMTQifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 123.0.0.0 on Mac OS 10.15.7
Viewport:  1307 x 958 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=123.0&resolution=1307x958&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=664786a68c65b1f1514cda68&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117965291_

**Comment by adamgall** [comment]
Closing, the language is clear as is
