### ISSUE TITLE
UX Feedback for new app home experience:

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1817]
UX Feedback for new app home experience:

A brand new user has no Safes show up in their view, so without the Featured section on the home page, I am currently stuck on the Home Screen. Not clear what I should do upon loading the app and no way to explore any further into the app. 
<details><summary>Browser metadata</summary>

```
Path:      /
Browser:   Safari 17.4.1 on iOS 17.4.1
Viewport:  390 x 671 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2F&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=664788c50d17a8fb0e5c3023&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117982974_

**Comment by adamgall** [comment]
Closing, nothing actionable here
