### ISSUE TITLE
"Unexpected error occurred" when executing a transaction.

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1818]
"Unexpected error occurred" error message when attempting to execute a transaction. 
*Transaction was created from Treasury screen "Send Assets" CTA 

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiIxYWRlNDdlNC0xMjQ5LTQ5MzctOTliNi0wNzUxZDJlMmNkMGEifQ==)
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiJhMzMzZmQxMi05MjNiLTQxOTItOWRkZC01NWUyMDYzM2ExODMifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /proposals/9?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Chrome 125.0.0.0 on Mac OS 10.15.7
Viewport:  1705 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fproposals%2F9%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=125.0&resolution=1705x1027&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/9?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=664788d47c57caf944ac99f8&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117983404_

**Comment by tomstuart123** [comment]
I also faced this problem. https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2118024264

We should p1 this

**Comment by adamgall** [comment]
This was a bug which has been fixed
