### ISSUE TITLE
Field issue

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1819]
**dara.khan left a comment:**

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiI1OTg3YzAzMi1hNzU5LTQ1MWQtOTIyYS01MDExZGY3MmFhODkifQ==)

Field case is mixed: some are title case, some are first-word case. Align to brand standard 
<details><summary>Browser metadata</summary>

```
Path:      /proposals/4?dao=sep:0x07D82EFcB2BEb403DB8B2B462289A7C7c2e3251f
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1192 x 816 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fproposals%2F4%3Fdao%3Dsep%3A0x07D82EFcB2BEb403DB8B2B462289A7C7c2e3251f&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1192x816&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/4?dao=sep:0x07D82EFcB2BEb403DB8B2B462289A7C7c2e3251f) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=66478a4d9e6c50fe6eb16a12&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117993797_

**Comment by tomstuart123** [comment]
@SpookyAction-BTC could you confirm what you mean?

**Comment by SpookyAction-BTC** [comment]
@tomstuart123 

Voting system
Snapshot taken
Voting power 

Are all regular case. The others are title-case ie both words capitalized. I saw it here could be in other sections too.

**Comment by adamgall** [comment]
This is fixed as of copy updates
