### ISSUE TITLE
Toaster/Notification size

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1821]
when I was delegating tokens on deskop, i saw a toast giving me some indication of what was happening. This was too small for a large deskop environment. If this should be a blocking modal, let's make it totally clear and large, if not let's put it in a more obvious and visible place. It would be great if it followed me around the app while it was in process.
<details><summary>Browser metadata</summary>

```
Path:      /proposals?dao=sep:0x3008B8D3e78bf0443683AbC52e35C11f4d785B27
Browser:   Chrome 125.0.0.0 on Mac OS 10.15.7
Viewport:  1861 x 1395 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fproposals%3Fdao%3Dsep%3A0x3008B8D3e78bf0443683AbC52e35C11f4d785B27&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=125.0&resolution=1861x1395&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals?dao=sep:0x3008B8D3e78bf0443683AbC52e35C11f4d785B27) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=66478e66977ec60329152410&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2118026733_

**Comment by adamgall** [comment]
Delegating tokens is not a blocking action.

The toast does follow you around the app.

Modifying toast behavior or size/location is out of scope for this redesign.

@tomstuart123 recommend we remove the `re-skin` label from this issue.

**Comment by tomstuart123** [comment]
happy with this. removed and we can look at toaster size later

**Comment by adamgall** [comment]
Closing in favor of https://github.com/decentdao/decent-interface/issues/1689
