### ISSUE TITLE
Search Multisig to modify govenrance --> button disabled

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1829]
When modifying an existing DAO's governance, the 'create azorious deployment proposal' button doesn't work.

I tried on both metamask and CB wallet and on two different DAOs.

Video on [slack here](https://decentdao.slack.com/archives/C06QZTUTKRC/p1716216999061209?thread_ts=1716211628.206369&cid=C06QZTUTKRC) - 

and DAO link here - https://deploy-preview-1578.app.dev.fractalframework.xyz/edit/governance?dao=sep:0xf0415067c0a385146C3CCB45f5E92a8530065C38

**Comment by Da-Colon** [comment]
I haven't been able to replicate this issue. But I did find that the `advanced option` for nonce isn't available here and we should properly add it.

**Comment by tomstuart123** [comment]
good call. Lets create an issue for it and p2 it

**Comment by Da-Colon** [comment]
Coolio, add issue #1844

**Comment by tomstuart123** [comment]
@Da-Colon - I was able to modify governance last time I tried this. Going to move it back into backlog

**Comment by adamgall** [comment]
@tomstuart123 i'm just going to close this, please re-open it if you're able to reproduce
