### ISSUE TITLE
Desktop Single Column width

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#1841]
Please update desktop layouts that use single columns to a smaller width. The request is to not expand the single column layouts to full width (like the 2 column layouts). See examples:

![Image](https://github.com/decentdao/fractal-interface/assets/18615633/5e490deb-f449-4153-bc59-a8948f969520)

![Image](https://github.com/decentdao/fractal-interface/assets/18615633/041bba05-34c5-4cdc-9163-8dbe9357cb7e)

In Figma
https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=3184%3A12393&t=jOfT063R1943NYz7-1

**Comment by adamgall** [comment]
Closing, stale
