### ISSUE TITLE
Add Nonce Setting for `Modify Governance` workflow for multisig DAOs

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#1844]

**Comment by Da-Colon** [comment]
@decentdao/design Got a question about placement. We need to add nonce to this workflow. Is this location good?

Context. This is when a Multisig DAO wants to change into a Azorius DAO setup. 



![Image](https://github.com/decentdao/fractal-interface/assets/38386583/12fef710-496c-4494-b0af-d420dd992dff)

**Comment by nicolaus-sherrill** [comment]
@Da-Colon looks good to me
