### ISSUE TITLE
is it possible to make "Read Docs" larger text so it is more obvious?

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1869]
is it possible to make "Read Docs" larger text so it is more obvious?

_Originally posted by @Delmslaugh in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524188_

**Comment by adamgall** [comment]
@nicolaus-sherrill please make the executive decision on which of this issue and #1880 to keep and kill

**Comment by nicolaus-sherrill** [comment]
@adamgall let's go with Parker and throw it in the footer. Be mindful of any users complaining they can't find the docs.
