### ISSUE TITLE
Redundant Safe Finders

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1871]
**UX**

A few points re: the redundant Safe finder text boxes here.

1.  I don't know that we need both in a single view
2. I don't like that I can't see or access the rest of the app when selecting that form field. I've never experienced that in an app UX before. I'd prefer to remove that effect.
2a. Side note: Why do two identical UI elements have different results when actively selected?

<img width="1630" alt="Screenshot 2024-05-22 at 09 09 02" src="https://github.com/decentdao/decent-interface/assets/13035147/2b2749ba-6a98-4b1d-9b85-26d5d2ff98ae">
<img width="1514" alt="Screenshot 2024-05-22 at 09 09 05" src="https://github.com/decentdao/decent-interface/assets/13035147/acae2e7c-d7fc-4f68-90e6-d58c9bbd7a14">

_Originally posted by @parkermccurley in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524235_

See discussion in original comment.

**Comment by adamgall** [comment]
I think this is on @decentdao/design to take the first pass at some new visuals: https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9525310

**Comment by tomstuart123** [comment]
yep lets leave in backlog until we connect @nicolaus-sherrill

**Comment by nicolaus-sherrill** [comment]
![Image](https://github.com/decentdao/decent-interface/assets/62394931/5b86a74b-fda6-415b-84b8-8d5f810b13f3)

**Comment by xraystyle1980** [comment]
Closing this issue and opening a new issue to address multiple design updates to home (updated design included below for reference)


![Image](https://github.com/decentdao/decent-interface/assets/18615633/c954b379-312f-45dd-b49e-806e847aef50)
