### ISSUE TITLE
"No Safes" copy and CTA updates

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1875]
@decentdao/product @decentdao/design 

I can see there are "No Safes", but I don't know what that means, or what I could do to rectify it. It likely _isn't_ "Create a Safe" since many of our prospective customers already have them.

1. Can we add some copy that tells the user what this list will contain?
2. Can we add some copy that tells the user what to do to add Safes to the list? Encourage them, conversationally. Ie "You haven't added any Safes yet! Search for a safe above to start tracking its governance activity" or similar.

<img width="1343" alt="Screenshot 2024-05-22 at 09 09 55" src="https://github.com/decentdao/decent-interface/assets/13035147/122bbdb1-75fa-44c4-9ae0-ca7f9dfffcfc">

_Originally posted by @parkermccurley in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524294_

See original comment thread.

**Comment by adamgall** [comment]
This is on @decentdao/design to take first pass

**Comment by xraystyle1980** [comment]
@adamgall This is ready. Please keep text on a single line until mobile. 
I'll remove the design label and move this back to ready.

![Image](https://github.com/decentdao/decent-interface/assets/18615633/6f7ac739-5abb-4088-bfa0-a1637afcdfee)



![Image](https://github.com/decentdao/decent-interface/assets/18615633/8fb26ed8-f1b9-4f56-b378-97f5099deb3d)



![Image](https://github.com/decentdao/decent-interface/assets/18615633/3dd0bba3-c024-4d80-9372-068d89e5ded1)
