### ISSUE TITLE
Mobile Metamask Wallet Connect connection issues

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1877]
I can't create a safe. 
Am I doing something wrong? I tried 5 times. 

<img width="862" alt="Screenshot 2024-05-22 at 18 23 35" src="https://github.com/decentdao/decent-interface/assets/162434678/39440fb3-5e24-40e5-acbc-bd17824ee209">
<img width="872" alt="Screenshot 2024-05-22 at 18 23 50" src="https://github.com/decentdao/decent-interface/assets/162434678/a830150f-1375-43d5-a82d-5c5156ecdc1c">

_Originally posted by @xanaramoss in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524367_

See original comment thread

**Comment by adamgall** [comment]
Mobile Metamask connected through WalletConnect on desktop results in app thinking that a signer is not connected.

David said he could not replicate with:
Desktop: Mac0s
Mobile: Android


We need to keep trying to duplicate this I suppose

**Comment by tomstuart123** [comment]
will keep trying to replicate. Move to backlog until then

**Comment by adamgall** [comment]
I was unable to reproduce this.

App OS: MacOS
App Browser: Chrome
Wallet OS: iOS
Wallet App: Metamask

**Comment by tomstuart123** [comment]
@adamgall was unable to replicate this issue that @xanaramoss faced

**Comment by xanaramoss** [comment]
@adamgall I recorded a video.
Happy that it's just me. Let's forget about this if no one else has the same issue. I'm not blocked. 


https://github.com/decentdao/decent-interface/assets/162434678/7561460e-de4f-48a2-920e-7dbc8eb5cea0

**Comment by adamgall** [comment]
@tomstuart123 recommend we close this, considering it's just one person's setup and not reproducable

**Comment by tomstuart123** [comment]
Lets close @adamgall

**Comment by adamgall** [comment]
heard the man
