### ISSUE TITLE
Read Docs changes

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1880]
@decentdao/product @decentdao/design 

"Read Docs" should just say "Docs" and be in the footer alongside the audit and release tag.

<img width="1020" alt="Screenshot 2024-05-22 at 09 33 30" src="https://github.com/decentdao/decent-interface/assets/13035147/84d0e6fd-e4b2-4d70-9479-59651730f3b8">

_Originally posted by @parkermccurley in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524484_

**Comment by nicolaus-sherrill** [comment]
FYI this and #1869 are conflicting pieces of feedback.

**Comment by adamgall** [comment]
@nicolaus-sherrill plz make the executive decision on which one of these two issues to keep and which to kill.

**Comment by adamgall** [comment]
@parkermccurley 

The copy updates that Tom/Nicolaus/Xana/Dara drove resulted in the "Read Docs" language turning into "Learn More" (see dev/prod site).

We also already have a link to the docs in the side navigation menu.

Does any of that information change your request to make this link say just "Docs" and be in the footer, too?

**Comment by tomstuart123** [comment]
Okay. As this has been merged and I'm offline the next couple of days lets not immediately pick this up... but I'd like your take @nicolaus-sherrill / @parkermccurley on if we keep it somewhere on home for mobile at least.

**Reasoning** - The original idea of having the docs so front and centre was that we don't have a marketing site right now to highlight what Decent is. Quick docs access fills this gap partially as it gives the user something to read arguments for why Decent needs to exist as well as how we work. 

On desktop I see the duplication and happy to remove as the sidebar is very visible. 

On mobile, however, I would push to keep the docs link somewhere more readily available. Users don't have many places to go right now if confused
