### ISSUE TITLE
Network switching woes

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1881]
Can't switch between networks on mobile through app dropdown network switcher. @adamgall this is the bug I screenshare'd my mobile devide during bug bash. This behavior was consistent on Coinbase Wallet AND Metamask. In CB Wallet, we disconnected existing dapps, refreshed the mobile app, and attempted to switch networks. This did not work. 
I attempted the same flow using Metamask and got similar results. In MM Wallet, I switched the network by hand but was still unable to switch networks in the decent app.

_Originally posted by @xraystyle1980 in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524502_

**Comment by tomstuart123** [comment]
@delma faced this issue. @adamgall and I couldn't replicate it and we offered an unblock solution

**Comment by tomstuart123** [comment]
@adamgall you're welcome to try one more time. As I couldn't replicate it and neither could @azadikoff , I'd recommend we close this

**Comment by adamgall** [comment]
i've never been able to replicate this one consistently. closing
