### ISSUE TITLE
Multisig Safe Settings Owner UX Updates

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1883]
![IMG_0807](https://github.com/decentdao/decent-interface/assets/62394931/6a20aa57-2341-4505-b66d-d949b3e692b6)

No way to unselect radio buttons. Worries me that someone might accidentally add or remove a signer while trying to do something else.

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524528_

See original comment thread.

**Comment by adamgall** [comment]
This is on @decentdao/design to take first pass at

**Comment by xraystyle1980** [comment]
@adamgall @nicolaus-sherrill the original Figma does not use radios and instead uses checkboxes. "Remove signer" is disabled unless user selects a signer to remove. (desktop pattern shown)
@nicolaus-sherrill do you want to revisit this pattern to explore adam's suggestion of adding a remove option next to each signer? 

![Image](https://github.com/decentdao/decent-interface/assets/18615633/00a3d806-6690-497c-865f-fedd7b78466d)

**Comment by adamgall** [comment]
@xraystyle1980 i would say we do need to re-look at this. currently we can only remove signers one at a time, so having the option of multiple check boxes isn't going to work
