### ISSUE TITLE
Multisig Safe Settings Mobile Tables

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1884]
![IMG_0808](https://github.com/decentdao/decent-interface/assets/62394931/5e69e5f1-e4a5-4fb0-bc95-a7a28f29e870)
@decentdao/design we need to optimize these mobile tables

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524539_

**Comment by adamgall** [comment]
This is on @decentdao/design to take first pass at

**Comment by xraystyle1980** [comment]
Propose using similar side scrolling pattern we're using for Treasury tables. Opening new issue with updated designs
