### ISSUE TITLE
Mobile overlapping Snapshot text

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1885]
I'm seeing overlapping text on proposals on mobile. ![image](https://github.com/decentdao/decent-interface/assets/295904/d7ad6772-5c74-4f4b-b183-83050102d1dc)

_Originally posted by @azadikoff in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524540_

**Comment by tomstuart123** [comment]
struggling to replicate this. Recommend we include in next bug bash.

If someone can replicate, please comment here and we'll move to ready

**Comment by adamgall** [comment]
@tomstuart123 i am unable to replicate this on Safari on iOS (which it looks like is the env in screenshot).

**Comment by tomstuart123** [comment]
lets keep this in backlog then until then

**Comment by adamgall** [comment]
Close it
