### ISSUE TITLE
Delegate button / modal improvements

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1886]
<img width="939" alt="image" src="https://github.com/decentdao/decent-interface/assets/163022070/c8f1986d-f927-4a8b-8076-d1696998d50e">

Is it possible to make Delegate pop up screen when I go to proposals? or make the button larger?

_Originally posted by @Delmslaugh in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524550_

**Comment by adamgall** [comment]
@decentdao/product @decentdao/design any feedback on this? Seems out of the scope of this redesign golive effort

**Comment by tomstuart123** [comment]
Design required

I would say now we have hats progress, this COULD (but lets see about SHOULD) be an option to be picked up before design moves onton whitelisting

**Comment by adamgall** [comment]
Stale, closing
