### ISSUE TITLE
Mobile content box padding

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1887]
![IMG_0809](https://github.com/decentdao/decent-interface/assets/62394931/ac101630-0ad8-4b57-a252-d0c0895da130)

![IMG_0811](https://github.com/decentdao/decent-interface/assets/62394931/310af5ec-2a6b-48a3-890e-c6c1c0a0cf84)

@decentdao/design I think we should reduce padding on these content boxes on mobile. Think we're doing 16px currently but 8px should suffice to give us more room for content to breathe.

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524613_

See original comment thread.

**Comment by adamgall** [comment]
@decentdao/design this is on yall to start, right?

**Comment by tomstuart123** [comment]
@decentdao/design - whenever you have a chance, lets pick this up. This is smaller than some of the other topics so easier to pick up

**Comment by adamgall** [comment]
Closing, stale
