### ISSUE TITLE
mobile dropdowns background blur

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1888]
![IMG_0810](https://github.com/decentdao/decent-interface/assets/62394931/aeb307a7-2ab7-4faf-ba92-588984c66788)
@decentdao/engineering mobile dropdowns don't have background blur

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524693_

**Comment by DarksightKellar** [comment]
Can't seem to reproduce this issue.

Chrome brower on android:
![Screenshot_20240523_134001_Chrome.jpg](https://github.com/decentdao/decent-interface/assets/7101382/a17d0260-9119-43ab-90a2-c56610c3760f)

Coinbase Wallet inapp browser:
![Screenshot_20240523_134242_Wallet.jpg](https://github.com/decentdao/decent-interface/assets/7101382/cd5116a6-7e41-4e2d-8f2f-81dc5ea62984)

**Comment by adamgall** [comment]
@nicolaus-sherrill can you please share your setup to reproduce this issue?

**Comment by azadikoff** [comment]
I am able to reproduce this issue with Coinbase Wallet on iOS. ![image](https://github.com/decentdao/decent-interface/assets/295904/136cdbfd-9aa6-4715-8377-77ac1da2c4ec)
