### ISSUE TITLE
Unable to delegate tokens to self on mobile

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1890]
Unable to delegate tokens to self on mobile. The app doesn't seem to trigger the mobile wallet
iOS, Metamask

*Works on desktop

https://github.com/decentdao/decent-interface/assets/18615633/6ab7836e-3032-4c51-95c7-d9dcfdfd33d9

_Originally posted by @xraystyle1980 in https://github.com/decentdao/decent-interface/discussions/1863#discussioncomment-9524756_

**Comment by azadikoff** [comment]
I was not able to reproduce the issue. Works fine for me

**Comment by adamgall** [comment]
I'm also unable to reproduce. @tomstuart123 close?

**Comment by tomstuart123** [comment]
Lets close @adamgall

**Comment by adamgall** [comment]
heard the man
