### ISSUE TITLE
Move mobile footer into menu

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#1912]
In response to Feedback button mobile #1904 

Apologies as this pattern never made it to handoff until now. This update moves the mobile footer in it's entirety to sit within the mobile menu. (see screenshot)

*The Report a Bug sentry button stays in place

[In Figma](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=3224-510&t=UvjQ9rNB30SilhlU-1)

![image](https://github.com/decentdao/decent-interface/assets/18615633/026fec0a-f07a-4fe7-8e8c-4e614628bfab)

**Comment by xraystyle1980** [comment]
@adamgall it looks like we'll need to keep the "Report a Bug" button where it is now based on comments from https://github.com/decentdao/decent-interface/issues/1874. 

Please confirm and I will update

**Comment by adamgall** [comment]
@xraystyle1980 yes, I implemented some changes already to fix the "shit covers other shit" problem, which have been signed off by @decentdao/product and @decentdao/engineering and merged into develop.

check it out here: https://github.com/decentdao/decent-interface/pull/1904

**Comment by xraystyle1980** [comment]
> @xraystyle1980 yes, I implemented some changes already to fix the "shit covers other shit" problem, which have been signed off by @decentdao/product and @decentdao/engineering and merged into develop.
> 
> check it out here: #1904
> 
> Recommend you undo the "Report a Bug in menu" changes in Figma, cause we won't be implementing that any time soon imo.
> 
> If you're ok with all of the above, then plz close this issue. Otherwise, let's talk about it!

@adamgall I updated my description and image above to NOT include the report a bug button. Can we meet in the middle and just move the audit, build, and endorsement into the mobile menu?

**Comment by adamgall** [comment]
I think we can do that @xraystyle1980 yes
