### ISSUE TITLE
Don't silently fail when attempting to create transaction and connect walled doesn't have enough funds for gas

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1916]
When the user is connected with a wallet that doesn't have enough funds for gas, the app will silently fail when clicking the transaction action button.

We should be showing an error toast, ideally with an appropriate error message.

At least, that's what happens on my setup: Chrome / Frame

**Comment by Da-Colon** [comment]
I'll need some kind guidance here. I'm not sure what error (or lack of error) you mean

**Comment by adamgall** [comment]
If you try to do a transaction using a wallet that has no gas funds (no ETH), an error stating "not enough funds for gas" appears in the console, but there's message presented to the user. From the user's point of view, clicking the button to trigger the transaction just "does nothing".
