### ISSUE TITLE
Favorites toggling doesn't work in mobile drawer view

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#1924]
When on mobile (and therefore the "My Safes" view uses the drawer), toggling a Favorite safe via the star icon doesn't toggle that Safe within the drawer.

Only after a refresh is the Safe properly reflected as added or removed from the My Safes drawer.

**Comment by Da-Colon** [comment]
Like clicking the star in the header? that mobile drawer? I don't have stars there?

![Image](https://github.com/decentdao/decent-interface/assets/38386583/f44c1e18-5b75-4bcd-a99e-6fe4c6a0fbd7)

**Comment by Da-Colon** [comment]
Deleted comment. I see what your saying. I got you now. I remember us trying to tackle this before, I'll take another look

**Comment by adamgall** [comment]
@Da-Colon Yeah sorry if it's not clear.

The issue only happen on mobile.

If you have a Safe loaded, and you click the "fav" star on that Safe Dashboard Main Card, that Safe does not appear in the My Safea drawer until after an app refresh.

**Comment by Da-Colon** [comment]
No worries @adamgall Its a doozy for sure...I know why its happening but haven't been able to come up with a solution yet.

**Comment by adamgall** [comment]
That's not a fun thing to hear

**Comment by Da-Colon** [comment]
I can 'fix' it but its not ideal. trying to come up with a better solution
