### ISSUE TITLE
`LabelWrapper` styling needs to updated

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#1954]
Input error text doesn't match design. See: https://github.com/decentdao/fractal-interface/issues/1600

**Comment by adamgall** [comment]
Oh, you can just transfer an issue between repos! Didn't know that. Nice job @github

**Comment by Da-Colon** [comment]
@mudrila Nice fine.

I'll link this comment https://github.com/decentdao/decent-interface/pull/1940#discussion_r1618785604 here to take a look at the typing for this component
