### ISSUE TITLE
Treasury page - Desktop - Remove assets horizontal scroll

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#1972]
Please update the Assets table in the desktop view to remove the horizontal scroll. 
Browser: Arc (Chromium)

See gif:
![Image](https://github.com/decentdao/decent-interface/assets/18615633/9ca3ea73-5462-44f0-8b22-95c6c49ff204)

**Comment by tomstuart123** [comment]
@xraystyle1980 - we do want this side scroll on mobile though due to the new design.

@decentdao/engineering is it possible to only have the side scroll at certain smaller responsiveness. If so, @xraystyle1980 what do you think ?

**Comment by tomstuart123** [comment]
Going to remove the bug label on this as it's more of a grey area
