### ISSUE TITLE
Fix votingStrategy typing

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#1982]
Caching has introduced a new "problem" edge case -- a proposal can be loaded before `votingStrategy` is loaded.
This issue was previously fixed in `QuoromBadge` (see lines 36 and 45), but in `ProposalSummary` (line 88), and probably other undiscovered areas, it's slightly more nuanced and will require a bit more thought.

A quick patch was to add a `votingStrategy?` null check, BUT this (and the implications of the previous fix) contradicts the non-nullable (but suddenly no longer true) typing of `votingStrategy`.

We need to figure out a more type-safe way to handle all of this.

**Comment by adamgall** [comment]
Closing, this is a symptom of bigger issues around state management.
