### ISSUE TITLE
Indicate pending created proposal in proposal list

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#1983]
In the time between the toast claiming a proposal has been successfully created and when the proposal _actually_ shows up on the UI, the proposal list should indicate that a recently created proposal has indeed been created and will be available soon.

**Comment by Da-Colon** [comment]
This delay is tough, Maybe we use some `temp` data in local storage that is check in some way, We have the tx hash I believe in the tx receipt so maybe when compare that and remove this storage item once the proposal is created?

**Comment by adamgall** [comment]
> This delay is tough, Maybe we use some `temp` data in local storage that is check in some way, We have the tx hash I believe in the tx receipt so maybe when compare that and remove this storage item once the proposal is shows up?

Yep, that's exactly what I was thinking too.

**Comment by DarksightKellar** [comment]
> This delay is tough, Maybe we use some `temp` data in local storage that is check in some way, We have the tx hash I believe in the tx receipt so maybe when compare that and remove this storage item once the proposal is shows up?

Yep that sounds workable. Lemme take this back on, thanks guys
