### ISSUE TITLE
WalletMenu Transition

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#1995]
Current WalletMenu doesn't have a transition added to it. Related to PR #1992

I attempted to get this work but was unable to.

I should also point out @DarksightKellar comment. https://github.com/decentdao/decent-interface/pull/1992#issuecomment-2163238731. As I noticed that the animation was different as well but couldn't pinpoint the WHY. Seems to be positional (where the menu's are located)

**Comment by adamgall** [comment]
Closing, stale
