### ISSUE TITLE
A.1/2 --> Roles + Payments Page (Hats + Sablier)

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#2020]
Roles + Payments is ready for handoff. These designs include the addition of a new page for the Decent<>Hats + Sablier integration.  
[In Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=3518-2724&t=gWQdcKdOt90B4icn-4)

**Comment by xraystyle1980** [comment]
@adamgall more context around the updates. My assumption is you and engineering will turn these into separate issues as you see fit.
- Updated [Sidebar](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=2521-5614&t=gWQdcKdOt90B4icn-4) and [Mobile Menu designs](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=3045-6525&t=gWQdcKdOt90B4icn-4) for Role (including new Roles icon)
- New component: Date Picker (component designs not formalized in design system yet)
- New component: Button Group "switcher" (component designs not formalized in design system yet)
- New component: Number Input (component designs not formalized in design system yet)
- Nice to have: Updated[ tooltip design](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=1549-9902&t=lNFLdg3l1JIikcZv-1) This updated tooltip is an inverse of the current tooltip and it pops really nice on dark backgrounds

**Comment by adamgall** [comment]
This is complete
