### ISSUE TITLE
Bug: Active Count Bug

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2082]
Final DAO Address: `0xf5175a81140f4d6950870C04DCebBC3974C95C9D`

As I was going through old DAOs. I pulled this one up and noticed that the Active Proposal Count is quite messed up.

![Image](https://github.com/decentdao/decent-interface/assets/38386583/3ae3c008-7f54-42cf-87fe-04666aec856a)

Refreshing fixes it. It must be happening switching DAOs so quickly

**Comment by adamgall** [comment]
Closing, it's a state issue which is bigger than this one issue.
