### ISSUE TITLE
`[roles-0.1.0]` Bug | Hat Id not valid

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2083]
After succesful execution of the proposal to create a new hat tree. The Toast pops up that the Hat ID is not valid and when visiting Roles page it is stuck in loading (hatTree === undefined). Fixes after refresh

**Comment by adamgall** [comment]
This needs a bit of a longer delay. Maybe "20" seconds. Search the codebase for "10_000"

**Comment by adamgall** [comment]
Moving this issue back to Ready. It was implemented and merged, but the hardcoded config value doesn't seem optimal.

Currently set to 10 seconds, let's move it to 20 seconds. Search codebase for "`10_000`"
