### ISSUE TITLE
`[roles-0.1.0]` Bug | Roles Data doesn't refresh

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2084]
When switching DAOs, Roles data is not refreshed and remains the Roles of the previous DAO until page refresh

**Comment by adamgall** [comment]
@Da-Colon I'm unable to replicate this on the current tip of `roles-0.1.1/desktop-and-other-updates`, at commit `bcdf9eddc455d444b02a4f0b9c22c9389b18df2f`.

@Da-Colon @mudrila @DarksightKellar are you?

**Comment by adamgall** [comment]
On a call with @DarksightKellar he experienced this during some unknown situation and/or scenario.

Still unsure how to replicate, but it happens...

**Comment by adamgall** [comment]
@DarksightKellar you mentioned that you know how to reproduce it. Please share those steps here

**Comment by DarksightKellar** [comment]
> @DarksightKellar you mentioned that you know how to reproduce it. Please share those steps here

Most reliable way I've found to repro:

- Be in a safe that has some roles
- Go back to homepage, create a new safe
- After safe is deployed, go to its roles page
- See that the roles from the previous safe shows here until a refresh

**Comment by adamgall** [comment]
Another way to replicate:

https://github.com/decentdao/decent-interface/issues/2179#issue-2430324329

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/decent-interface/pull/2188
