### ISSUE TITLE
`[roles-0.1.0]` Update UI for Tabs for Desktop Drawer and Forms

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2095]
Currently Tabs design in the app are styled to the Mobile Specs even on desktop. but For Desktop and The Vesting Form We will need a new variant/component to match designs

https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=3898-7379&t=PvJ1W5ty2r4Gdc3t-4

**Comment by adamgall** [comment]
@Da-Colon this was in the work you did last night, right?

**Comment by Da-Colon** [comment]
No sir.
