### ISSUE TITLE
Proposal creation failed when "adding one role; editing one role"

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#2114]
- [x] Adding one role
- [ ] Adding a second role and edit one role - 'proposal failed'
- [x] Then just added a second role - tick
- [x] Then just editing role one - tick
- [ ] Then tried again add one role and edit role - still 'proposal failed'. Seems consistent
- Setup is on mobile with cbwallet

https://decentdao.slack.com/archives/C06QZTUTKRC/p1720540378763629?thread_ts=1720540198.702399&cid=C06QZTUTKRC

originally posted by @tomstuart123

**Comment by adamgall** [comment]
I (@adamgall) experienced this same behavior/bug during my own independent testing during the bug bash

**Comment by tomstuart123** [comment]
Ye it seems it doesn't work on azorius but works fine of MSig

**Comment by Da-Colon** [comment]
Yeah confirmed last night that MSig works. I'll take a look at a azorius setup and test

**Comment by Da-Colon** [comment]
Hmmm. I was able to do this with MSig and Token DAO with no issues?

**Comment by adamgall** [comment]
Closing because neither @Da-Colon nor @adamgall can replicate (we used to be able to). 

@tomstuart123 , please re-open if you can still replicate this bug.
