### ISSUE TITLE
`[roles-0.1.0]` Add tooltip copy and 'Learn more' Link to Payroll form

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2153]
<img width="704" alt="Screenshot 2024-07-30 at 11 15 22 AM" src="https://github.com/user-attachments/assets/354cd71f-170a-4ecd-8734-a4b23c8a1a52">

This exists in the "Payment Stream" section of the Edit page of a Role.

- The green "Learn More" link needs a target
- the tooltip (displayed in screenshot above) needs copy

**Comment by Da-Colon** [comment]
@decentdao/design @decentdao/product Do we have copy/links for these?

**Comment by tomstuart123** [comment]
**Re; Learn More links** - This should lead to our docs on the stream page @Da-Colon / @adamgall . [i.e. Link for you to use here ](https://docs.decentdao.org/app/user-guide/roles-and-streaming/streaming-payroll-and-vesting). However, this is text is incomplete so @SpookyAction-BTC lets DM about timelines for this today.

**Re; Tooltip** - My take: we take pieces of copy from the Sablier site but tweaked to our needs

E.g.
**- For add payment tooltip -** 'Payments on a per-second basis; powered by Sablier'.
**- For Cliff tooltip** - 'Assets continue to accrue but aren't yet claimable here.'

For the middle one, we can draft something new
**- For Schedule tooltip -** 'Use either duration periods or the Date Range Picker' 


 @nicolaus-sherrill / @xraystyle1980 / @xanaramoss we need copy for the three tooltips in the above. Could you look at my very brief draft and tweak if its needed

![Screenshot 2024-08-06 at 14 31 20](https://github.com/user-attachments/assets/3791056d-004b-476f-a1eb-944f9f9a0928)

**Comment by adamgall** [comment]
Closed via #2235
