### ISSUE TITLE
Role Status on Edit - Tags aren't visible in table during editing'

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#2160]
Situation - when a role is being edited but the table is visible and 'Create a proposal' hasn't been clicked.

In the designs - See [here](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=3898-14720&t=GLZRxteGl4JlYeLp-0) and below. As you can see tags of 'Updated' 'removed' etc are visible on edit.

![Image](https://github.com/user-attachments/assets/33f8babc-925c-4ee7-a9a7-70753753ab18)

In app, I added 'LIVEEDITMADE' to the role title but 'updated' doesn't appear

![Image](https://github.com/user-attachments/assets/7ca10ce3-eb70-4773-91cb-39dae4d1a64d)

It does appear on the next screen but having it on the table would be helpful for the user

![Image](https://github.com/user-attachments/assets/46c017dd-be7a-45bc-8f35-34f1ac21eb56)

**Comment by adamgall** [comment]
@Da-Colon this issue is completed, right?

**Comment by adamgall** [comment]
This is completed.
