### ISSUE TITLE
`[roles-0.1.0]` Remove payment Component from Create Proposal UI

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2172]

**Comment by adamgall** [comment]
@Da-Colon what's the status of this issue? Is it linked to a PR?

**Comment by Da-Colon** [comment]
Ah yes should have been

**Comment by Da-Colon** [comment]
Ah sorry, brain fart. Forgot I assigned this to myself. I'm on it

**Comment by adamgall** [comment]
closed via https://github.com/decentdao/decent-interface/pull/2208
