### ISSUE TITLE
`[roles-0.1.0]` Asset Tooltip `z-index`

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2173]
<img width="266" alt="Screenshot 2024-07-23 at 1 49 12 PM" src="https://github.com/user-attachments/assets/8dda4b82-1d73-42fe-8e9b-68f731614ce6">

z-index issue with tooltip and `Select Asset` dropdown

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/issues/2165#issuecomment-2245998282_

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/decent-interface/pull/2216
