### ISSUE TITLE
`[roles-0.1.0]` Payroll/Vesting data not showing

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2174]
![screenshot](https://camo.githubusercontent.com/b5e082879a1dae941c7e11dc78dee8604c04d8c956315fad5652d0a535470929/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f6959324e685a44466d5a6d55745a4455345a5330304d6a4d344c574a695932457459324d774f544d784e5467314e574e6d496977695a4756776247393558326c6b496a6f694e6a59355a6d526c4f4451325a5463305a4441774d4441344e4451355a574e6a49697769615751694f6949795a546b785a57526c5953316b4f47597a4c545135596a4d7459544d784e6930794f474a6a4d6a63324d47497a4f54636966513d3d)
> 
> I created a these 2 roles at the same time/same proposal however none of the payment + vesting was applied. (the admin role should have payroll + vesting and the designer role should have payroll)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a0077ed54a9c2b2d9383a5&resolution=resolved)

I experienced this same issue.

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/issues/2165#issuecomment-2246206795_

**Comment by adamgall** [comment]
@Da-Colon what's the deal with this issue, is it linked to a PR?

**Comment by Da-Colon** [comment]
Yep. This was taken care of in this PR as well.
