### ISSUE TITLE
`[roles.0.1.0]` Roles Create Page missing Footer

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2175]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiJlMTQ2OWQwZS1jYjU3LTRkMTQtODJmMS1iNWU0ZDk0N2EyYTYifQ==)

Please add footer component below submit proposal button
<details><summary>Browser metadata</summary>

```
Path:      /roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1465 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1465x1027&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a0120b209146382d4b6d9b&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/decent-interface/issues/2165#issuecomment-2246250761_

**Comment by adamgall** [comment]
closed via https://github.com/decentdao/decent-interface/pull/2208
