### ISSUE TITLE
`[roles.0.1.0]` Unable to encode proposal data

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2176]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiI0MGE0ZjBhNy0wOGQyLTQzM2ItYWJmYy0yNDkyZjljMzg1MzUifQ==)

Getting Toast message with "Unable to encode proposal data" (see recording)

<details><summary>Browser metadata</summary>

```
Path:      /roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a01352ad6e393870041784&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/decent-interface/issues/2165#issuecomment-2246259246_

**Comment by Da-Colon** [comment]
This happens because of a negative number being calculated when todays date is selected and being used in a `encodeFunctionData` call which throws an error

**Comment by DarksightKellar** [comment]
This should be a non-issue now, with the updated streams, right? @Da-Colon

**Comment by adamgall** [comment]
Closing because it's been fixed
