### ISSUE TITLE
`[roles.0.1.0]` Table shifts when navigating

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2177]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiI5ZmU3ZTcxMC1jNDMwLTRkNzMtOGZmZS01ZDMxNDFiM2E0YjYifQ==)

When I enter edit mode, the table columns shift to the left. I assume this is to make room for the status badge. But I wonder if we could handle this change a little more elegantly? i.e., less of a dramatic shift

<details><summary>Browser metadata</summary>

```
Path:      /roles/edit?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1465 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1465x1027&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a00883036db235850a725b&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/decent-interface/issues/2165#issuecomment-2246151603_

**Comment by adamgall** [comment]
@Da-Colon this is in review, but is there an associated PR?

**Comment by Da-Colon** [comment]
yeah sorry, meant to circle back sooner. PR added that it was fixed in. (removing the hardcoded `w="10%` and moving it to the name section.

This can be closed

**Comment by adamgall** [comment]
Closing!
