### ISSUE TITLE
`[Design Handoff | Payments]` Update Role Details card

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2230]
Figma: 
- https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=5004-3061&m=dev
- https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=5004-3280&m=dev

**Comment by Da-Colon** [comment]
Should call out who picks up this card. There is a shared component with the form. I'll be leaving this component out of the `form updates` PR. With a placeholder and a todo (I'll need to click something). Keep that in mind when creating this component. 

https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=5077-15481&m=dev

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/decent-interface/pull/2250
