### ISSUE TITLE
Importing wrapped token like `wstETH` still leads to wrapping token once more with our own wrapper, which seem to be wrong

### ISSUE THREAD

**Issue by mudrila** [decentdao/decent-interface#2253]
See https://github.com/decentdao/decent-interface/pull/2248#issuecomment-2290021241

**Comment by adamgall** [comment]
Well wait a second. Was the original "Wrapped token" wrapped in the sense that it happened via our app? Or, is "Wrapped liquid staked ETH 2.0" the official name of the original token that you're bringing to Decent.

What I'm asking is, did you originally start with a token called "liquid staked ETH 2.0"?

**Comment by adamgall** [comment]
Agreed, thanks Kirill
