### ISSUE TITLE
Navigation button flicker

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#2257]
When using the expanded sidebar navigation, the buttons clicked have a split second of a white border being added when click on and off. See attached video. 
I dug in a little and noticed a 0.5 value being applied to the border for only a split second when clicking. Watch the box model preview in the bottom right.

https://github.com/user-attachments/assets/d1a8239d-4d02-4702-ab3a-d847260e2fad

**Comment by DarksightKellar** [comment]
> I'm thinking if that's worth adjusting non-active links to also have 1px transparent border to avoid layout shift

@mudrila I think it's actually very worth it. That, or a 1px border with same colour as background, whichever looks better as a whole
