### ISSUE TITLE
MultisigFreezeGuard Timelockable issue

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#2271]
Myosin Multisig Safes with MultisigFreezeGuard aren't entering "timelockable" state in Decent app, leading to transactions which say that can be executed, failing

https://app.decentdao.org/proposals?dao=base:0x0c14aA2d34C0E13Bbe441963e4de2EeAef4abeD2

https://app.safe.global/settings/modules?safe=base:0x0c14aA2d34C0E13Bbe441963e4de2EeAef4abeD2

**Comment by Da-Colon** [comment]
duplicate issue
