### ISSUE TITLE
Consistent empty pages

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/decent-interface#2288]
Please update all "empty" pages site wide and across all viewports. Empty pages are any pages in the app a user can navigate to but no data has been added that would be visible in the UI.
Notable changes:
- All empty pages should use the body-base text style at color neutral-6
- None of the empty cards should have a clickable call to action in the message
- All of the empty cards should have the new raised effect
- Padding on desktop empty cards should be 24px 
- Padding on mobile empty cards should be 16px

![image](https://github.com/user-attachments/assets/6308bac4-fac5-485a-868c-13ba6a52df37)
![image](https://github.com/user-attachments/assets/eef792c2-ec78-44db-b2bd-3bf45462f4db)
![image](https://github.com/user-attachments/assets/a7185af1-9623-4e89-b044-7ac5dff9271e)
![image](https://github.com/user-attachments/assets/aec64d37-6cb5-4604-80e7-b56e8deafdae)
![image](https://github.com/user-attachments/assets/50f01037-f7fa-4d7b-9762-1b02759ec6d5)

**Comment by tomstuart123** [comment]
@mudrila could you elaborate. I actually have no problem with 'empty box having no CTA'.

Unless I misunderstand, we don't follow this pattern in-app currently. Do we?

**Comment by mudrila** [comment]
> @mudrila could you elaborate. I actually have no problem with 'empty box having no CTA'.
> 
> 
> 
> Unless I misunderstand, we don't follow this pattern in-app currently. Do we?
> 
> 
> 
> 

We do have a quick action for creating proposal and creating template, as far as I know
I might be wrong but I feel like I heard from you that you find it pretty useful and wanted to have it somewhere else 😅

**Comment by tomstuart123** [comment]
ah I didn't have my wallet connected when I had zero proposals. Once i connected the wallet, I saw the relevant prompt below
<img width="1399" alt="Screenshot 2024-09-02 at 15 39 58" src="https://github.com/user-attachments/assets/14970969-8677-418e-b228-8a24de9953d4">

@xraystyle1980 , no issue from me. I agree that pointing them to the above (as we do in roles) is much cleaner.

**Comment by tomstuart123** [comment]
@mudrila any reason we can't move this into 'ready'?

**Comment by mudrila** [comment]
We can move it to "Ready" - I guess it wasn't there cause there was no triaging, but we should be good
