### ISSUE TITLE
InValid HatId when Idle

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/decent-interface#2298]
Was sitting on the `Edit` roles page and after some time the Network ErrorBoundary Page is shown and this error.

![Image](https://github.com/user-attachments/assets/ad7534e3-ddda-47b5-b409-9d3a80d7a032)

I see this error as well

![Image](https://github.com/user-attachments/assets/b7c4f5e9-9d76-4e6e-84a2-7c9921b1e39b)

Timed it at idle for:
1 m: 30 s
2m: 53s
3m: 4s

**Comment by adamgall** [comment]
This issue seems to be stale, closing
