### ISSUE TITLE
ERC20 voting strategy on "wrapped" token DAOs likely not correct

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#2403]
We have a strategy built and deployed for "wrapped" ERC20 voting tokens, called `LinearERC20WrappedVoting`.

However, we don't import or use this strategy anywhere in our frontend project.

The differences in the `LinearERC20WrappedVoting` and `LinearERC20Voting` strategies are related to how "total token amount" is determined, which affects quorum calculations.

I wouldn't be surprised if proposals and voting logic and math was buggy in our app for ERC20 token voting DAOs with a wrapped governance token.

**Comment by Da-Colon** [comment]
Ripping it out see #2570
