### ISSUE TITLE
(Global) replace <meta> copy with “Decent enables transparent, accountable governance that evolves as fast as you do.” when linking to app.

### ISSUE THREAD

**Issue by adamgall** [decentdao/decent-interface#2512]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1422ee9c5bc28075aee0efe4b6411623

**Comment by Da-Colon** [comment]
Not complete, sorry unrelated to My PR I have up

**Comment by adamgall** [comment]
Agree with @DarksightKellar , closing in favor of #2517
