### ISSUE TITLE
Move “Templates” to  DAO Home or Create Proposal workflow

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2521]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1422ee9c5bc280dc87b1ef413bd46cc5

**Comment by nicolaus-sherrill** [comment]
@decentdao/engineering this is going to take some design work. Need to think through how to include templates into the proposal creation flow — does this bleed into actions modal menu?

**Comment by nicolaus-sherrill** [comment]
@DarksightKellar looks like it.
