### ISSUE TITLE
Safe dashboard UX updates

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2523]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1422ee9c5bc280cdb602ddd6c5483487

**Comment by nicolaus-sherrill** [comment]
Proposals UI merged into Home here: https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=0-1&t=zPw6DYYA1Y20B1ki-1

**Comment by DarksightKellar** [comment]
Thanks @nicolaus-sherrill 

For engineering:
I intend to pick this up, but won't assign myself just yet till I get back to work tomorrow. If anyone else wanted to pick it up, feel free to do so

**Comment by nicolaus-sherrill** [comment]
@DarksightKellar I overlooked the requirement to add the Delegate button to this screen as well. Designs have been updated to include that button.
