### ISSUE TITLE
Role Detail view updates

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2525]
Note: These updates are NOT for the edit role views. That's in another issue

https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc280099faacc4ae900d241

**Comment by nicolaus-sherrill** [comment]
@decentdao/engineering given Parker's direction to make the member address copyable, I'm testing adding a pill around the component to make it more obvious that it is a thing to interact with: <img width="430" alt="Inactive Role Details - Terms" src="https://github.com/user-attachments/assets/46361e86-08b4-461f-9400-a6e2ac74d871">

What do you all think?

Prototype here: https://www.figma.com/proto/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?page-id=3518%3A2361&node-id=6652-14594&node-type=frame&viewport=4929%2C3438%2C1.73&t=lyrXDOoY7XBAKzZz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6652%3A14594

**Comment by nicolaus-sherrill** [comment]
BTW this is following MetaMask's lead here, based on their latest UI update to improve signature clarity: https://metamask.io/news/latest/metamask-ui-update-signature-redesign/
