### ISSUE TITLE
Update Claim payments

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2527]
Looks like this will require significant redesign?
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc28095b5f1db4b81532500

**Comment by nicolaus-sherrill** [comment]
As I am interpreting this feedback, which touches on basically every part of the component, this is a call for a redesign.

**Comment by xanaramoss** [comment]
@DarksightKellar Withdraw component updated: https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.1.1?node-id=5254-726&t=BHknyzHTt8zKAEKz-4
