### ISSUE TITLE
Add voting schema “ERC-20”, “ERC-721”, “Multisig” to the listed subdaos

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2530]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13f2ee9c5bc2801bbacad5d7e7fd659e

Probably means the hierarchy page's subdao nodes should indicate what type they are. Correct if wrong

**Comment by Da-Colon** [comment]
Closed
