### ISSUE TITLE
Proposal templates updates

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2534]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1432ee9c5bc280389299f136c409c9cc

**Comment by nicolaus-sherrill** [comment]
@decentdao/engineering this is going to take some design work. Need to think through how to include templates into the proposal creation flow — does this bleed into actions modal menu?
