### ISSUE TITLE
Create safe progress bar

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2535]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc280c0a4c3d24d8ed9c1e3

**Comment by nicolaus-sherrill** [comment]
@decentdao/engineering I believe this will need some design work first. We will get updates over ASAP
