### ISSUE TITLE
Signers/Owners config updates

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2538]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#1432ee9c5bc2808dacbec0a44140af89

**Comment by DarksightKellar** [comment]
This will require some design input (if it hasn't happened already) @decentdao/design

**Comment by xanaramoss** [comment]
@DarksightKellar I'm waiting for the last design approval but I think we can get going:
https://www.figma.com/design/BFnj2DbieCOzc2gWZHIS2d/Owners?node-id=194-14475&t=puKfP5MEQmFuPW5a-4

<img width="780" alt="Screenshot 2024-11-26 at 11 04 43" src="https://github.com/user-attachments/assets/6cd6780b-d965-433a-baf9-c02d6871c0ce">
