### ISSUE TITLE
Create Safe/Compose Governance copy updates

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2541]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc28046b88ce7d721cc2ef9

**Comment by DarksightKellar** [comment]
Waiting for design response

**Comment by DarksightKellar** [comment]
@decentdao/design See: https://www.notion.so/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?d=1442ee9c5bc2803ebf86001c42613341&pvs=4#13e2ee9c5bc2802ca1b7eee4d526b6df. Basically need new UI for length-of-time (not range) input in the form DD:HH:mm:ss

**Comment by xanaramoss** [comment]
> @decentdao/design See: https://www.notion.so/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?d=1442ee9c5bc2803ebf86001c42613341&pvs=4#13e2ee9c5bc2802ca1b7eee4d526b6df. Basically need new UI for length-of-time (not range) input in the form DD:HH:mm:ss

@DarksightKellar do you know examples of good practices for this?
This is what I came up with:
<img width="958" alt="Screenshot 2024-11-21 at 17 56 20" src="https://github.com/user-attachments/assets/803c6703-8dac-4034-a414-b526152c3425">

**Comment by xanaramoss** [comment]
@DarksightKellar we have 2 options for now:
**1. Inputs for DD:HH:mm:ss**
<img width="716" alt="Screenshot 2024-11-22 at 14 31 10" src="https://github.com/user-attachments/assets/b39d4704-133e-4242-b7ce-94

**2. One Input for days**
<img width="740" alt="Screenshot 2024-11-22 at 14 31 19" src="https://github.com/user-attachments/assets/ff678ab3-1539-4cdf-bfef-fda4b8a21708">
ca31070629">


Nicolaus is waiting to get feedback on voting period times. - [Slack message.](https://decentdao.slack.com/archives/C06QZTUTKRC/p1732265463848739?thread_ts=1732265013.582599&cid=C06QZTUTKRC)

[Updated Designs on Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=206-14838&t=AwGVRNuN70m2Qtwr-4)
[Components on design system ](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.1.1?m=auto&node-id=3682-2628&t=X7JW5BPOx7tobAtp-1)

Let me know if you have any questions

**Comment by xanaramoss** [comment]
@DarksightKellar I think option 2 is the winner. I added a label to the input so the user knows it’s in “days,” and 7 should be the pre-determined number.

For testing purposes maybe adding a time input makes the process more efficient? But only visible on dev.
<img width="1256" alt="Screenshot 2024-11-26 at 11 12 32" src="https://github.com/user-attachments/assets/9db42952-721e-4e29-be38-0b654930a67a">
