### ISSUE TITLE
Update logotype to two color lilac + off-white version

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2543]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#a67c1ae7292a4f5285443c9483ebfb94

There probably is, or will be, a related design issue for this
cc @decentdao/design just in case

**Comment by nicolaus-sherrill** [comment]
@DarksightKellar we have our designs updated with this. Do you need the 2 color logo asset?

**Comment by DarksightKellar** [comment]
> designs updated with this. Do you need the 2 color

@nicolaus-sherrill Yes please + link to the asset itself, thanks

**Comment by xanaramoss** [comment]
> > designs updated with this. Do you need the 2 color
> 
> @nicolaus-sherrill Yes please + link to the asset itself, thanks

[Figma File](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.1.1?node-id=1321-10986&t=4vSg6A3IUCUqgpby-4)

![Logomark](https://github.com/user-attachments/assets/2a1b454f-9bf7-4d26-982b-cf2a2272eda0)
![Signature](https://github.com/user-attachments/assets/85594f93-ed51-4558-9e18-eb817589bb3f)
