### ISSUE TITLE
Add “Add DAO” option to “My DAOs” dropdown. When clicked, opens Modal with option to either Search or Create DAO

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2544]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc280c8b20aeaf4b1636fc7

**Comment by Da-Colon** [comment]
@decentdao/design Is working on feedback cycles right now.

**Comment by Da-Colon** [comment]
Closed, pivoting
