### ISSUE TITLE
Send Bug Reports to Slack, Notion, or wherever necessary to respond quickly

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2546]
https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#13e2ee9c5bc2807fb790c05087c6a411

**Comment by adamgall** [comment]
Bug reports which come from the feedback button in the bottom right corner of the app already go directly to the #builders channel on Slack.
