### ISSUE TITLE
Wrap/unwrap functionality UX + UI

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/decent-interface#2570]
There's wrap/unwrap code in the original proposals page that is missing in the home page's proposals UI (and probably in designs too). 

Need to zero in on what the should look and behave like.

**Comment by DarksightKellar** [comment]
cc @decentdao/design @decentdao/engineering

**Comment by Da-Colon** [comment]
Rip it out for now.

**Comment by Da-Colon** [comment]
There will be somewhere in the useGovernanceContract that we can rip the Contract out from
